import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { HeresyGameManager } from '../src/heresyGameManager.js';

function fixture(count=5){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-v1-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:()=>0.9});const {code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('locked compositions are exact and roles come from JSON',()=>{const f=fixture();try{for(let n=5;n<=12;n++){const ids=f.manager.presetFor(n);assert.equal(ids.length,n);for(const id of ids)assert.ok(f.manager.role(id));const specials=ids.filter(x=>x!=='imperial-citizen');assert.equal(new Set(specials).size,specials.length);}assert.deepEqual(f.manager.presetFor(5),['murderer','priest','interrogator','chirurgeon','imperial-citizen']);}finally{f.close();}});

test('state never exposes numeric drift',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const state=f.manager.state(f.code,'p0');assert.equal(JSON.stringify(state).includes('"drift"'),false);assert.ok(state.me.role?.id);assert.equal(state.players.filter(p=>p.role).length,1);}finally{f.close();}});

test('lobby state does not expose role composition but does expose compositionLabel',()=>{const f=fixture();try{const state=f.manager.state(f.code,'p0');assert.equal(state.phase,'lobby');assert.equal('composition' in state,false);assert.equal(state.compositionLabel,'5-operative doctrine');assert.equal(JSON.stringify(state).includes('Murderer'),false);assert.equal(JSON.stringify(state).includes('Priest'),false);assert.equal(state.players.some(p=>p.role),false);}finally{f.close();}});

test('catalyst converts only a Black-zone target and failure is silent',()=>{const f=fixture(10);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const recruiter=f.manager.players(f.code).find(p=>p.role_id==='recruiter'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'loyalist');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=20,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'heretic');}finally{f.close();}});

test('target-first wrong interrogation cripples once and charges target voters',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.game(f.code).phase,'night');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);assert.equal(f.manager.player(f.code,target.player_code).alive,1);for(const p of voters)assert.equal(f.manager.player(f.code,p.player_code).drift,1);assert.equal(f.manager.player(f.code,target.player_code).drift,0);const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');}finally{f.close();}});

test('right interrogation cleanses all living players',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='heretic'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=?').run(f.code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);assert.ok(f.manager.players(f.code).filter(p=>p.alive).every(p=>p.drift===4));const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).witnessedDrift,-1);}finally{f.close();}});

test('sermon limits are enforced from data',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const priest=f.manager.players(f.code).find(p=>p.role_id==='priest'),target=f.manager.players(f.code).find(p=>p.player_code!==priest.player_code);f.manager.db.prepare('INSERT INTO hr_usage VALUES(?,?,?,?)').run(f.code,priest.player_code,'hymn',2);assert.throws(()=>f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'hymn'}),/limit/);}finally{f.close();}});

test('all dead players share one graveyard and living players are denied',()=>{const f=fixture();try{const dead='p1';f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(f.code,dead);f.manager.sendMessage(f.code,dead,'graveyard','Ashes remember.');assert.equal(f.manager.historyMessages(f.code,dead,'graveyard').messages.length,1);assert.throws(()=>f.manager.historyMessages(f.code,'p0','graveyard'),/denied/);}finally{f.close();}});

test('sleep reduces drift only when no action was submitted',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizenLike=f.manager.players(f.code).find(p=>f.manager.role(p.role_id).actions.night?.kind==='sleep');if(citizenLike){f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=? AND player_code=?').run(f.code,citizenLike.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizenLike.player_code).drift,4);}}finally{f.close();}});

test('same target on consecutive days lynches, kills, and reveals faction publicly',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0);assert.equal(after.cripple_tier,3);assert.ok(f.manager.historyMessages(f.code,'p0','public').messages.some(m=>/revealed loyalist/.test(m.body)));const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'lynch');for(const p of voters)assert.equal(f.manager.player(f.code,p.player_code).drift,4);}finally{f.close();}});

test('full-flow consecutive-day escalation via advance()',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);assert.equal(f.manager.game(f.code).phase,'day');assert.equal(f.manager.game(f.code).round,1);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).phase,'night');assert.equal(f.manager.game(f.code).round,1);assert.equal(f.manager.player(f.code,target.player_code).alive,1);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).phase,'day');assert.equal(f.manager.game(f.code).round,2);assert.equal(f.manager.game(f.code).day_stage,'vote');for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,target.player_code).alive,0);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,3);assert.ok(f.manager.historyMessages(f.code,'p0','public').messages.some(m=>/revealed loyalist/.test(m.body)));const events=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id").all(f.code);const parsed=events.map(e=>JSON.parse(e.payload));assert.equal(parsed[0].outcome,'interrogate');assert.equal(parsed[0].round,1);assert.equal(parsed[1].outcome,'lynch');assert.equal(parsed[1].round,2);assert.equal(parsed[1].crippleTier,3);assert.equal(parsed[1].alignmentRevealed,'loyalist');assert.equal(parsed[1].witnessedDrift,1);for(const p of voters){const drift=f.manager.player(f.code,p.player_code).drift;const result=parsed[1].voterResults.find(r=>r.voter===p.player_code);assert.ok(result);assert.equal(result.driftDelta,f.manager.config.drift.WRONG_LYNCH);}}finally{f.close();}});

test('skip-round resets escalation — same target after skip is fresh interrogation',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3),skippers=f.manager.players(f.code).slice(0,3);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).round,2);for(const p of skippers)f.manager.vote(f.code,p.player_code,'skip');f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).phase,'night');f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).round,3);for(const p of voters.filter(x=>f.manager.player(f.code,x.player_code).alive))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');assert.equal(JSON.parse(event.payload).round,3);assert.equal(JSON.parse(event.payload).crippleTier,1);assert.equal(f.manager.player(f.code,target.player_code).alive,1);}finally{f.close();}});

test('different-target-between resets escalation — back to original is fresh interrogation',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const targetA=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),targetB=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'&&p.player_code!==targetA.player_code),voters=f.manager.players(f.code).filter(p=>p.player_code!==targetA.player_code&&p.player_code!==targetB.player_code).slice(0,3);for(const p of voters)f.manager.vote(f.code,p.player_code,targetA.player_code);f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,targetA.player_code).cripple_tier,1);f.manager.advance(f.code,'p0');for(const p of voters)f.manager.vote(f.code,p.player_code,targetB.player_code);f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');assert.equal(f.manager.game(f.code).round,3);for(const p of voters.filter(x=>f.manager.player(f.code,x.player_code).alive))f.manager.vote(f.code,p.player_code,targetA.player_code);f.manager.advance(f.code,'p0');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');assert.equal(JSON.parse(event.payload).target,targetA.player_code);assert.equal(f.manager.player(f.code,targetA.player_code).alive,1);}finally{f.close();}});

test('skip majority stands the day down without drift',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const voters=f.manager.players(f.code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,'skip');f.manager.resolve(f.code,true);assert.equal(f.manager.game(f.code).phase,'night');assert.ok(f.manager.players(f.code).every(p=>p.drift===0));const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'skip');assert.equal(JSON.parse(event.payload).reason,'skip-majority');}finally{f.close();}});

test('Day 3 Heretics below cap receive the locked spike',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');const heretic=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.applyHereticCap(f.code,3);assert.equal(f.manager.player(f.code,heretic.player_code).drift,3);}finally{f.close();}});

test('Heretic parity ends the game',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const loyalists=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code IN (?,?,?)').run(f.code,loyalists[0].player_code,loyalists[1].player_code,loyalists[2].player_code);assert.equal(f.manager.finishIfWon(f.code),true);assert.equal(f.manager.game(f.code).winner,'heretic');}finally{f.close();}});

test('admin overview and detail expose actual hidden game state',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const overview=f.manager.adminOverview();assert.equal(overview.games.some(g=>g.code===f.code),true);assert.ok(overview.roles.length>=5);const detail=f.manager.adminGame(f.code);assert.equal(detail.game.code,f.code);assert.equal(detail.players.length,5);assert.equal(detail.players.some(p=>p.role&&p.faction&&Number.isInteger(p.drift)),true);assert.ok(Array.isArray(detail.messages));assert.ok(Array.isArray(detail.events));}finally{f.close();}});

test('L1: every living citizen auto-drifts -1 per night (floor 0)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');assert.ok(citizen,'citizen exists');assert.equal(citizen.drift,0);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,0,'floors at 0');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=3 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,2,'reduces from 3 to 2');}finally{f.close();}});

test('L1: crippled citizen still sleeps (drift -1)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');f.manager.db.prepare('UPDATE hr_players SET drift=5,cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,4,'crippled citizen still gets sleep');}finally{f.close();}});

test('L1: dead citizen does not sleep',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');f.manager.db.prepare('UPDATE hr_players SET drift=3,alive=0 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,3,'dead citizen unchanged');}finally{f.close();}});

test('L1: citizen cannot submit a night action',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');assert.throws(()=>f.manager.submitAction(f.code,citizen.player_code,{targetCode:'p0'}),/no active action/);}finally{f.close();}});

test('L3: protect blocks night kill — attacker wastes action',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1,'chirurgeon paid drift');}finally{f.close();}});

test('L3: protect blocks heretical-catalyst — catalyst fails silently',()=>{const f=fixture(10);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),recruiter=f.manager.players(f.code).find(p=>p.role_id==='recruiter'),loyalist=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.db.prepare('UPDATE hr_players SET drift=20 WHERE game_code=? AND player_code=?').run(f.code,loyalist.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:loyalist.player_code});f.manager.submitAction(f.code,recruiter.player_code,{targetCode:loyalist.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,loyalist.player_code).faction,'loyalist','catalyst was blocked');}finally{f.close();}});

test('L3: rotation rule rejects same target on consecutive nights',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code}),/consecutive nights/);}finally{f.close();}});

test('L3: rotation allows same target after a gap (night 1 → night 3)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon'),other=f.manager.players(f.code).find(p=>p.player_code!==chirurgeon.player_code&&p.player_code!==target.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:other.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=3 WHERE code=?").run(f.code);assert.doesNotThrow(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code}));}finally{f.close();}});

test('L3: rotation rejects self-protect on consecutive nights',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code}),/consecutive nights/);}finally{f.close();}});

test('L3: self-protect is allowed on night 1',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon');assert.doesNotThrow(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code}));}finally{f.close();}});

test('L3: crippled chirurgeon silently rejected (no error, no drift)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,chirurgeon.player_code);const result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,0,'crippled chirurgeon paid no drift');}finally{f.close();}});

test('L3: chirurgeon pays +1 drift regardless of whether protect fires',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1);}finally{f.close();}});

test('L3: chirurgeon receives no success/failure notification (no private message)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const privateMessages=f.manager.db.prepare("SELECT * FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,chirurgeon.player_code);assert.equal(privateMessages.length,1,'chirurgeon has only a role-announcement private message, no protect notification');}finally{f.close();}});

test('L3: chirurgeon self-protect works — self survives night kill',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'chirurgeon survived self-protect');}finally{f.close();}});

test('L3: protect resolves even when chirurgeon is killed the same night',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon'&&p.player_code!==murderer.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,0,'chirurgeon was killed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'protected target survived');}finally{f.close();}});

test('L5: arbitrator dies when proxying a target who is night-killed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');}finally{f.close();}});

test('L5: arbitrator pays +1 drift when proxying',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,1,'arbitrator paid drift');}finally{f.close();}});

test('L5: arbitrator proxy resolves when protected target survives (no-kill)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,1,'arbitrator paid drift');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');}finally{f.close();}});

test('L5: crippled arbitrator is silently rejected (no error)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=?,cripple_tier=2 WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);const result=f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,0,'crippled arbitrator paid no drift');}finally{f.close();}});

test('L5: arbitrator rotation rejects same target on consecutive nights',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code}),/consecutive nights/);}finally{f.close();}});

test('L5: arbitrator self-proxy is not allowed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);assert.throws(()=>f.manager.submitAction(f.code,arb.player_code,{targetCode:arb.player_code}),/Choose another player/);}finally{f.close();}});

test('L5: chirurgeon + arbitrator on same target → arbitrator dies first',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],chirurgeon=players[3],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('chirurgeon','loyalist',f.code,chirurgeon.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'chirurgeon survived');}finally{f.close();}});

test('L5: no L3 regression — existing chirurgeon protect still works',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived via chirurgeon protect');assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1,'chirurgeon paid drift');}finally{f.close();}});

function fixtureL4(randomFn,count=8){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-l4-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:randomFn});const{code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

function setupL4Target(f,targetDrift,skipTargetSleep=false){f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),l4=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('novice-psychic','loyalist',f.code,l4.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('imperial-citizen','loyalist',f.code,target.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=? WHERE game_code=? AND player_code=?').run(targetDrift,f.code,target.player_code);if(skipTargetSleep)f.manager.db.prepare('UPDATE hr_players SET skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);return{l4,target};}

test('L4: novice-psychic investigates a Green-zone target returns Green string',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const greenHint=f.manager.hints(f.code).green;assert.ok(msgs.some(m=>m.body===greenHint),'L4 received green hint');assert.equal(msgs.length,2,'L4 received role announcement + investigation result');const otherMsgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code!=?").all(f.code,l4.player_code);assert.ok(!otherMsgs.some(m=>m.body===greenHint),'No other player received the hint');}finally{f.close();}});

test('L4: novice-psychic investigating Yellow target — 100 rolls, noise rate ≈ 10%',()=>{let flips=0;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,6);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const yellowHint=f.manager.hints(f.code).yellow;if(msgs[1]?.body!==yellowHint)flips++;}finally{f.close();}}assert.ok(flips>=5&&flips<=15,`Expected ~10 flips, got ${flips}`);});

test('L4: novice-psychic investigating Orange target — 100 rolls, noise rate ≈ 20%',()=>{let flips=0;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,11);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const orangeHint=f.manager.hints(f.code).orange;if(msgs[1]?.body!==orangeHint)flips++;}finally{f.close();}}assert.ok(flips>=12&&flips<=28,`Expected ~20 flips, got ${flips}`);});

test('L4: novice-psychic investigating Black target — flips are always Red (only adjacent zone)',()=>{let flips=0,allRed=true;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,20,true);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const blackHint=f.manager.hints(f.code).black;const redHint=f.manager.hints(f.code).red;const hint=msgs[1]?.body;if(hint!==blackHint){flips++;if(hint!==redHint)allRed=false;}}finally{f.close();}}assert.ok(flips>=40&&flips<=60,`Expected ~50 flips, got ${flips}`);assert.ok(allRed,'All noise flips returned Red (only adjacent zone to Black)');});

test('L4: crippled novice-psychic is silently rejected (no error, no drift)',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,l4.player_code);const result=f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(result.kind,'drift-hint');assert.equal(f.manager.player(f.code,l4.player_code).drift,0,'crippled L4 paid no drift');}finally{f.close();}});

test('L4: novice-psychic self-investigate is rejected',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const l4=f.manager.players(f.code)[6];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('novice-psychic','loyalist',f.code,l4.player_code);assert.throws(()=>f.manager.submitAction(f.code,l4.player_code,{targetCode:l4.player_code}),/Choose another player/);}finally{f.close();}});

test('L4: novice-psychic pays +1 drift when night action resolves',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,l4.player_code).drift,1,'L4 paid +1 drift');}finally{f.close();}});

test('T1 cripple recovers after 1 round of no re-interrogation — night action works on next night',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),voters=f.manager.players(f.code).filter(p=>p.player_code!==chirurgeon.player_code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,chirurgeon.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).cripple_tier,1,'T1 applied');assert.equal(f.manager.player(f.code,chirurgeon.player_code).tier1_until_round,1,'tier1_until_round is current round');assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'still alive');// Night 1: T1 active — action silently rejected
const target=f.manager.players(f.code).find(p=>p.player_code!==chirurgeon.player_code&&p.alive);
const night1Result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});
assert.equal(night1Result.silent,true,'T1 blocks action');
f.manager.resolve(f.code,true);
// Day 2: T1 should have cleared during night→day transition
assert.equal(f.manager.player(f.code,chirurgeon.player_code).cripple_tier,0,'T1 cleared');
assert.equal(f.manager.player(f.code,chirurgeon.player_code).tier1_until_round,null,'tier1_until_round cleared');
// Night 2: chirurgeon can act again
f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);
const result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});
assert.equal(result.silent,undefined,'action is not silently rejected');
assert.equal(result.kind,'protect','action kind is protect');
  }finally{f.close();}
});

test('L7: Psyker fires kill → target dies, Psyker at +15 drift',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code);f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'target died');assert.equal(f.manager.player(f.code,psyker.player_code).drift,16,'Psyker at +16 drift (+15 kill +1 witness)');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Chirurgeon protect on target → kill blocked, kill consumed, drift still applied',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,psyker.player_code).drift,15,'Psyker paid drift');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Arbitrator bodyguard redirects kill → Arbitrator dies, Psyker at +15 drift',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),arbitrator=f.manager.players(f.code).find(p=>p.role_id==='arbitrator'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code);f.manager.submitAction(f.code,arbitrator.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arbitrator.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,psyker.player_code).drift,16,'Psyker at +16 drift (+15 kill +1 witness)');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Saboteur trap on Psyker → +20 total drift (15+5), kill NOT consumed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code&&p.player_code!==saboteur.player_code);f.manager.submitAction(f.code,saboteur.player_code,{targetCode:psyker.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,psyker.player_code).drift,20,'Psyker at +20 drift');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived — kill blocked by actor trap');}finally{f.close();}});

test('L7: Execute on Sight — Interrogator T2 scan on Psyker at Red zone kills Psyker, kill NOT consumed',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),interrogator=f.manager.players(f.code).find(p=>p.role_id==='interrogator'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET drift=15 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,interrogator.player_code,{targetCode:psyker.player_code,variant:'T2'});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,psyker.player_code).alive,0,'Psyker died from Execute on Sight');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived — kill never fired');}finally{f.close();}});

test('L7: T1 crippled Psyker cannot fire — recovers next night and kill works',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=1,tier1_until_round=1 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed from blocked attempt');f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,psyker.player_code).cripple_tier,0,'T1 cleared');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed after recovery');}finally{f.close();}});

test('L7: T2 crippled Psyker permanently blocked — T2 does not recover',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,psyker.player_code).cripple_tier,2,'T2 persists');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);}finally{f.close();}});

test('L7: killLimit honored — Psyker cannot fire a second time',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target1=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.submitAction(f.code,psyker.player_code,{targetCode:target1.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'first kill consumed');const target2=f.manager.players(f.code).find(p=>p.alive&&p.faction==='heretic'&&p.player_code!==target1.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target2.player_code}),/once per game/);}finally{f.close();}});

test('L7: at 5p and 6p, Sanctioned Psyker is NOT in the composition',()=>{const f=fixture();try{const ids5=f.manager.presetFor(5);assert.equal(ids5.includes('sanctioned-psyker'),false,'Psyker not at 5p');const ids6=f.manager.presetFor(6);assert.equal(ids6.includes('sanctioned-psyker'),false,'Psyker not at 6p');}finally{f.close();}});

test('L7: at 7p, Sanctioned Psyker IS in the composition exactly once',()=>{const f=fixture();try{const ids7=f.manager.presetFor(7);assert.ok(ids7.includes('sanctioned-psyker'),'Psyker at 7p');assert.equal(ids7.filter(x=>x==='sanctioned-psyker').length,1,'exactly one Psyker');}finally{f.close();}});

