import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { HeresyGameManager } from '../src/heresyGameManager.js';

function fixture(count=5){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-v1-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:()=>0.9});const {code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('locked compositions are exact and roles come from JSON',()=>{const f=fixture();try{for(let n=5;n<=12;n++){const ids=f.manager.presetFor(n);assert.equal(ids.length,n);for(const id of ids)assert.ok(f.manager.role(id));const specials=ids.filter(x=>x!=='imperial-citizen');assert.equal(new Set(specials).size,specials.length);}assert.deepEqual(f.manager.presetFor(5),['murderer','priest','interrogator','chirurgeon','imperial-citizen']);}finally{f.close();}});

test('state never exposes numeric drift',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const state=f.manager.state(f.code,'p0');assert.equal(JSON.stringify(state).includes('"drift"'),false);assert.ok(state.me.role?.id);assert.equal(state.players.filter(p=>p.role).length,1);}finally{f.close();}});

test('lobby state does not expose role composition',()=>{const f=fixture();try{const state=f.manager.state(f.code,'p0');assert.equal(state.phase,'lobby');assert.equal('composition' in state,false);assert.equal('compositionLabel' in state,false);assert.equal(JSON.stringify(state).includes('Murderer'),false);assert.equal(JSON.stringify(state).includes('Priest'),false);assert.equal(state.players.some(p=>p.role),false);}finally{f.close();}});

test('catalyst converts only a Black-zone target and failure is silent',()=>{const f=fixture(10);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const recruiter=f.manager.players(f.code).find(p=>p.role_id==='recruiter'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'loyalist');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=20,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'heretic');}finally{f.close();}});

test('interrogation escalates and T1 charges target plus living witnesses',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code)[1];f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='target' WHERE code=?").run(f.code);f.manager.event(f.code,'day-mode',{mode:'interrogate'});for(const p of f.manager.players(f.code))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);assert.equal(f.manager.player(f.code,target.player_code).drift,1);assert.ok(f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).every(p=>p.drift===1));f.manager.respondInterrogation(f.code,target.player_code,'resist');f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='target' WHERE code=?").run(f.code);f.manager.event(f.code,'day-mode',{mode:'interrogate'});for(const p of f.manager.players(f.code))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,2);}finally{f.close();}});

test('sermon limits are enforced from data',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const priest=f.manager.players(f.code).find(p=>p.role_id==='priest'),target=f.manager.players(f.code).find(p=>p.player_code!==priest.player_code);f.manager.db.prepare('INSERT INTO hr_usage VALUES(?,?,?,?)').run(f.code,priest.player_code,'hymn',2);assert.throws(()=>f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'hymn'}),/limit/);}finally{f.close();}});

test('all dead players share one graveyard and living players are denied',()=>{const f=fixture();try{const dead='p1';f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(f.code,dead);f.manager.sendMessage(f.code,dead,'graveyard','Ashes remember.');assert.equal(f.manager.historyMessages(f.code,dead,'graveyard').length,1);assert.throws(()=>f.manager.historyMessages(f.code,'p0','graveyard'),/denied/);}finally{f.close();}});

test('sleep reduces drift only when no action was submitted',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizenLike=f.manager.players(f.code).find(p=>f.manager.role(p.role_id).actions.night?.kind==='sleep');if(citizenLike){f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=? AND player_code=?').run(f.code,citizenLike.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizenLike.player_code).drift,4);}}finally{f.close();}});

test('lynch cripples to Tier 3, kills, and reveals faction publicly',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare("UPDATE hr_games SET phase='day',round=1,day_stage='target' WHERE code=?").run(f.code);f.manager.event(f.code,'day-mode',{mode:'lynch'});for(const p of f.manager.players(f.code))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0);assert.equal(after.cripple_tier,3);assert.ok(f.manager.historyMessages(f.code,'p0','public').some(m=>/revealed loyalist/.test(m.body)));}finally{f.close();}});

test('Day 3 Heretics below cap receive the locked spike',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');const heretic=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.applyHereticCap(f.code,3);assert.equal(f.manager.player(f.code,heretic.player_code).drift,3);}finally{f.close();}});

test('Heretic parity ends the game',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const loyalists=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code IN (?,?,?)').run(f.code,loyalists[0].player_code,loyalists[1].player_code,loyalists[2].player_code);assert.equal(f.manager.finishIfWon(f.code),true);assert.equal(f.manager.game(f.code).winner,'heretic');}finally{f.close();}});

test('admin overview and detail expose actual hidden game state',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const overview=f.manager.adminOverview();assert.equal(overview.games.some(g=>g.code===f.code),true);assert.ok(overview.roles.length>=5);const detail=f.manager.adminGame(f.code);assert.equal(detail.game.code,f.code);assert.equal(detail.players.length,5);assert.equal(detail.players.some(p=>p.role&&p.faction&&Number.isInteger(p.drift)),true);assert.ok(Array.isArray(detail.messages));assert.ok(Array.isArray(detail.events));}finally{f.close();}});
