import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { HeresyGameManager } from '../src/heresyGameManager.js';

function fixture(count=5){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-v1-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:()=>0.9});const {code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('locked compositions are exact and roles come from JSON',()=>{const f=fixture();try{for(let n=5;n<=12;n++){const ids=f.manager.presetFor(n);assert.equal(ids.length,n);for(const id of ids)assert.ok(f.manager.role(id));const specials=ids.filter(x=>x!=='imperial-citizen');assert.equal(new Set(specials).size,specials.length);}assert.deepEqual(f.manager.presetFor(5),['murderer','priest','interrogator','chirurgeon','imperial-citizen']);}finally{f.close();}});

test('state never exposes numeric drift',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const state=f.manager.state(f.code,'p0');assert.equal(JSON.stringify(state).includes('"drift"'),false);assert.ok(state.me.role?.id);assert.equal(state.players.filter(p=>p.role).length,1);}finally{f.close();}});

test('lobby state does not expose role composition but does expose compositionLabel',()=>{const f=fixture();try{const state=f.manager.state(f.code,'p0');assert.equal(state.phase,'lobby');assert.equal('composition' in state,false);assert.equal(state.compositionLabel,'5-operative doctrine');assert.equal(JSON.stringify(state).includes('Murderer'),false);assert.equal(JSON.stringify(state).includes('Priest'),false);assert.equal(state.players.some(p=>p.role),false);}finally{f.close();}});

test('catalyst converts only a Black-zone target and failure is silent',()=>{const f=fixture(10);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const recruiter=f.manager.players(f.code).find(p=>p.role_id==='recruiter'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'loyalist');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=20,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,recruiter.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).faction,'heretic');}finally{f.close();}});

// ── Tiered Lynch (tiered-lynch.md v1.0.0) ──────────────────────────────────
// Supersedes the old consecutive-day escalation entirely: outcome is
// decided same-day by what fraction of LIVING votes the leader clears.
// >=60% (ceil) executes outright; any positive count below that
// interrogates instead — repeatably, with no drift cost beyond the cripple
// tier (the old wrong/right-interrogation drift rows are gone).

test('Tiered Lynch: below 60% interrogates — no drift to voters, no drift to target, skips next night',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.game(f.code).phase,'night','2/5=40%, below threshold — interrogate, not execute');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);assert.equal(f.manager.player(f.code,target.player_code).alive,1);assert.equal(f.manager.player(f.code,target.player_code).skip_next_night,1,'target loses their next night action');for(const p of voters)assert.equal(f.manager.player(f.code,p.player_code).drift,0,'no drift to voters — interrogation has no drift cost');assert.equal(f.manager.player(f.code,target.player_code).drift,0,'no drift to target either');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');assert.equal(JSON.parse(event.payload).witnessedDrift,0);}finally{f.close();}});

test('Tiered Lynch: interrogating a Heretic target also carries no drift (cleansing rule removed)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='heretic'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2);f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=?').run(f.code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);assert.ok(f.manager.players(f.code).filter(p=>p.alive).every(p=>p.drift===5),'drift unchanged for everyone — no cleansing');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).witnessedDrift,0);}finally{f.close();}});

test('Tiered Lynch: 5p exact boundary — 3/5 (60%) executes outright, no prior day needed',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'3/5=60% clears the threshold on the FIRST day, not the second');assert.equal(after.cripple_tier,3);assert.ok(f.manager.historyMessages(f.code,'p0','public').messages.some(m=>/revealed loyalist/.test(m.body)));const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'lynch');}finally{f.close();}});

test('Tiered Lynch: 6p at 4/6 (67%) executes; 3/6 (50%) only interrogates',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters.slice(0,3))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'3/6=50% — below the ceil(6*0.6)=4 threshold, interrogate only');f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters.slice(0,4))f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'4/6=67% clears the threshold');}finally{f.close();}});

// ── Tiered Lynch v1.1.0: consecutive-interrogation escalation ─────────────
// The same suspect interrogated on two CONSECUTIVE days now escalates to a
// kill on the second day — the cabal gets exactly one probe cycle to
// defend a suspect before the table's second look is a verdict, not
// another probe. This supersedes v1.0.0's "repeatable, never escalates"
// behavior for the specific same-target-two-days-running case; a target
// hit non-consecutively (with any gap — a skip day, a different target in
// between, or a direct kill) still just gets a fresh interrogation.

test('Tiered Lynch v1.1.0: same suspect interrogated two consecutive days — day 2 escalates to a kill',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1,'day 2: first interrogation, tier 1');assert.equal(f.manager.player(f.code,target.player_code).alive,1);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'day 3: same suspect again — escalates to execution, not a third interrogation');assert.equal(after.cripple_tier,3);assert.ok(f.manager.historyMessages(f.code,'p0','public').messages.some(m=>/revealed loyalist/.test(m.body)),'alignment revealed, same as a >=60% kill');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'lynch');}finally{f.close();}});

test('Tiered Lynch v1.1.0: a skip day in between resets the escalation — third day is a fresh interrogation',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2),everyone=f.manager.players(f.code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of everyone)f.manager.vote(f.code,p.player_code,'skip');f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=3 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=4,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,1,'the intervening skip day broke the streak — round 4 is a fresh interrogation, not an escalation');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');}finally{f.close();}});

test('Tiered Lynch v1.1.0: a different target interrogated in between resets the escalation for the original suspect',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');const loyalists=f.manager.players(f.code).filter(p=>p.faction==='loyalist'),targetA=loyalists[0],targetB=loyalists[1],voters=f.manager.players(f.code).filter(p=>p.player_code!==targetA.player_code&&p.player_code!==targetB.player_code).slice(0,2);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,targetA.player_code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,targetB.player_code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=3 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=4,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,targetA.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,targetA.player_code).alive,1,'targetB breaking in between means targetA is not "the previous day\'s leader" on round 4 — fresh interrogation');}finally{f.close();}});

test('Tiered Lynch v1.1.0: a >=60% kill does not carry an escalation into the next day',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const targetA=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),targetB=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'&&p.player_code!==targetA.player_code),voters=f.manager.players(f.code).filter(p=>p.player_code!==targetA.player_code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,targetA.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,targetA.player_code).alive,0,'3/5=60% kills outright on day 2');const twoVoters=f.manager.players(f.code).filter(p=>p.alive&&p.player_code!==targetB.player_code).slice(0,2);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of twoVoters)f.manager.vote(f.code,p.player_code,targetB.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,targetB.player_code).alive,1,'a fresh target the day after a kill is just a normal interrogation — no residual escalation state');}finally{f.close();}});

test('Tiered Lynch v1.1.0: atRiskTarget is exposed in state()/spectate() after an interrogation, and clears once the streak breaks',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2),bystander=f.manager.players(f.code).find(p=>p.player_code!==target.player_code&&!voters.some(v=>v.player_code===p.player_code));f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.state(f.code,bystander.player_code).atRiskTarget,target.player_code,'publicly visible — anyone can see who is one interrogation away from execution');assert.equal(f.manager.spectate(f.code).atRiskTarget,target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=3,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,'skip');f.manager.resolve(f.code,true);assert.equal(f.manager.state(f.code,bystander.player_code).atRiskTarget,null,'a skip day clears the flag');}finally{f.close();}});

test('Tiered Lynch: a target already at T3 still gets interrogated — tier saturates but the night-action skip still fires',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2);f.manager.db.prepare('UPDATE hr_players SET cripple_tier=3 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.game(f.code).phase,'night','not blocked — the old T3 hard-block is gone');const after=f.manager.player(f.code,target.player_code);assert.equal(after.cripple_tier,3,'capped, does not overflow past 3');assert.equal(after.skip_next_night,1,'still loses the night action');assert.equal(after.alive,1);const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'interrogate');}finally{f.close();}});

test('Tiered Lynch: tiebreaker (higher drift) still resolves the target when the fraction is below 60%',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const loyalists=f.manager.players(f.code).filter(p=>p.faction==='loyalist'),targetA=loyalists[0],targetB=loyalists[1],voterA=f.manager.players(f.code).find(p=>p.player_code!==targetA.player_code&&p.player_code!==targetB.player_code),voterB=f.manager.players(f.code).find(p=>p.player_code!==targetA.player_code&&p.player_code!==targetB.player_code&&p.player_code!==voterA.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=3 WHERE game_code=? AND player_code=?').run(f.code,targetA.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=9 WHERE game_code=? AND player_code=?').run(f.code,targetB.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);f.manager.vote(f.code,voterA.player_code,targetA.player_code);f.manager.vote(f.code,voterB.player_code,targetB.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,targetB.player_code).cripple_tier,1,'higher-drift target wins the 1-1 tie');assert.equal(f.manager.player(f.code,targetA.player_code).cripple_tier,0);assert.equal(f.manager.player(f.code,targetB.player_code).alive,1,'1/5=20% — nowhere near 60%, so still interrogation, not execution');}finally{f.close();}});

test('Tiered Lynch: full-flow via advance() — Day 2 interrogates below threshold, Day 3 executes once 60% is reached',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!=='p0'),twoVoters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,2),threeVoters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code).slice(0,3);f.manager.advance(f.code,'p0');// Night 1
f.manager.advance(f.code,'p0');// Day 2
assert.equal(f.manager.game(f.code).round,2);for(const p of twoVoters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,target.player_code).alive,1);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);f.manager.advance(f.code,'p0');// Day 3
assert.equal(f.manager.game(f.code).round,3);for(const p of threeVoters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.advance(f.code,'p0');const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'3/5=60% on Day 3 alone is sufficient — no two-day commitment needed');assert.equal(after.cripple_tier,3);const events=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id").all(f.code);const parsed=events.map(e=>JSON.parse(e.payload));assert.equal(parsed[0].outcome,'skip');assert.equal(parsed[0].reason,'day1-no-vote');assert.equal(parsed[1].outcome,'interrogate');assert.equal(parsed[1].round,2);assert.equal(parsed[2].outcome,'lynch');assert.equal(parsed[2].round,3);}finally{f.close();}});

test('sermon limits are enforced from data',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const priest=f.manager.players(f.code).find(p=>p.role_id==='priest'),target=f.manager.players(f.code).find(p=>p.player_code!==priest.player_code);f.manager.db.prepare('INSERT INTO hr_usage VALUES(?,?,?,?)').run(f.code,priest.player_code,'hymn',2);assert.throws(()=>f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'hymn'}),/limit/);}finally{f.close();}});

test('all dead players share one graveyard and living players are denied',()=>{const f=fixture();try{const dead='p1';f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(f.code,dead);f.manager.sendMessage(f.code,dead,'graveyard','Ashes remember.');assert.equal(f.manager.historyMessages(f.code,dead,'graveyard').messages.length,1);assert.throws(()=>f.manager.historyMessages(f.code,'p0','graveyard'),/denied/);}finally{f.close();}});

test('sleep reduces drift only when no action was submitted',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizenLike=f.manager.players(f.code).find(p=>f.manager.role(p.role_id).actions.night?.kind==='sleep');if(citizenLike){f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=? AND player_code=?').run(f.code,citizenLike.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizenLike.player_code).drift,4);}}finally{f.close();}});


test('skip majority stands the day down without drift',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const voters=f.manager.players(f.code).slice(0,3);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,'skip');f.manager.resolve(f.code,true);assert.equal(f.manager.game(f.code).phase,'night');assert.ok(f.manager.players(f.code).every(p=>p.drift===0));const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).outcome,'skip');assert.equal(JSON.parse(event.payload).reason,'skip-majority');}finally{f.close();}});

test('Day 3 Heretics below cap receive the locked spike',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');const heretic=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.applyHereticCap(f.code,3);assert.equal(f.manager.player(f.code,heretic.player_code).drift,3);}finally{f.close();}});

test('Heretic parity ends the game',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const loyalists=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code IN (?,?,?)').run(f.code,loyalists[0].player_code,loyalists[1].player_code,loyalists[2].player_code);assert.equal(f.manager.finishIfWon(f.code),true);assert.equal(f.manager.game(f.code).winner,'heretic');}finally{f.close();}});

test('admin overview and detail expose actual hidden game state',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.changeDrift(f.code,'p0',5,'admin-test');const driftEvent=JSON.parse(f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='drift' ORDER BY id DESC LIMIT 1").get(f.code).payload);assert.equal(driftEvent.before,0);assert.equal(driftEvent.after,5);assert.equal(driftEvent.round,1);assert.equal(driftEvent.phase,'day');const overview=f.manager.adminOverview();const summary=overview.games.find(g=>g.code===f.code);assert.ok(summary);assert.equal(summary.averageDrift,1);assert.equal(summary.maxPlayerDrift,5);assert.ok(overview.roles.length>=5);const detail=f.manager.adminGame(f.code);assert.equal(detail.game.code,f.code);assert.equal(detail.players.length,5);assert.equal(detail.players.find(p=>p.playerCode==='p0').drift,5);assert.equal(detail.players.some(p=>p.role&&p.faction&&Number.isInteger(p.drift)),true);assert.ok(Array.isArray(detail.messages));assert.ok(Array.isArray(detail.events));}finally{f.close();}});

test('L1: every living citizen auto-drifts -1 per night (floor 0)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');assert.ok(citizen,'citizen exists');assert.equal(citizen.drift,0);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,0,'floors at 0');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=3 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,2,'reduces from 3 to 2');}finally{f.close();}});

test('L1: crippled citizen still sleeps (drift -1)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');f.manager.db.prepare('UPDATE hr_players SET drift=5,cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,4,'crippled citizen still gets sleep');}finally{f.close();}});

test('L1: dead citizen does not sleep',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');f.manager.db.prepare('UPDATE hr_players SET drift=3,alive=0 WHERE game_code=? AND player_code=?').run(f.code,citizen.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,citizen.player_code).drift,3,'dead citizen unchanged');}finally{f.close();}});

test('L1: citizen cannot submit a night action',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const citizen=f.manager.players(f.code).find(p=>p.role_id==='imperial-citizen');assert.throws(()=>f.manager.submitAction(f.code,citizen.player_code,{targetCode:'p0'}),/no active action/);}finally{f.close();}});

test('L3: protect blocks night kill — attacker wastes action',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1,'chirurgeon paid drift');}finally{f.close();}});

test('L3: protect blocks heretical-catalyst — catalyst fails silently',()=>{const f=fixture(10);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),recruiter=f.manager.players(f.code).find(p=>p.role_id==='recruiter'),loyalist=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.db.prepare('UPDATE hr_players SET drift=20 WHERE game_code=? AND player_code=?').run(f.code,loyalist.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:loyalist.player_code});f.manager.submitAction(f.code,recruiter.player_code,{targetCode:loyalist.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,loyalist.player_code).faction,'loyalist','catalyst was blocked');}finally{f.close();}});

test('L3: rotation rule rejects same target on consecutive nights',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code}),/consecutive nights/);}finally{f.close();}});

test('L3: rotation allows same target after a gap (night 1 → night 3)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon'),other=f.manager.players(f.code).find(p=>p.player_code!==chirurgeon.player_code&&p.player_code!==target.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:other.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=3 WHERE code=?").run(f.code);assert.doesNotThrow(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code}));}finally{f.close();}});

test('L3: rotation rejects self-protect on consecutive nights',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code}),/consecutive nights/);}finally{f.close();}});

test('L3: self-protect is allowed on night 1',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon');assert.doesNotThrow(()=>f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code}));}finally{f.close();}});

test('L3: crippled chirurgeon silently rejected (no error, no drift)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,chirurgeon.player_code);const result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,0,'crippled chirurgeon paid no drift');}finally{f.close();}});

test('L3: chirurgeon pays +1 drift regardless of whether protect fires',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1);}finally{f.close();}});

test('L3: chirurgeon receives no success/failure notification (no private message)',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const privateMessages=f.manager.db.prepare("SELECT * FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,chirurgeon.player_code);assert.equal(privateMessages.length,1,'chirurgeon has only a role-announcement private message, no protect notification');}finally{f.close();}});

test('L3: chirurgeon self-protect works — self survives night kill',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:chirurgeon.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'chirurgeon survived self-protect');}finally{f.close();}});

test('L3: protect resolves even when chirurgeon is killed the same night',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon'&&p.player_code!==murderer.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:chirurgeon.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,0,'chirurgeon was killed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'protected target survived');}finally{f.close();}});

test('L5: arbitrator dies when proxying a target who is night-killed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');}finally{f.close();}});

test('L5: arbitrator pays +1 drift when proxying',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,1,'arbitrator paid drift');}finally{f.close();}});

test('L5: arbitrator proxy resolves when protected target survives (no-kill)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,1,'arbitrator paid drift');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');}finally{f.close();}});

test('L5: crippled arbitrator is silently rejected (no error)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=?,cripple_tier=2 WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);const result=f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(f.manager.player(f.code,arb.player_code).drift,0,'crippled arbitrator paid no drift');}finally{f.close();}});

test('L5: arbitrator rotation rejects same target on consecutive nights',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code}),/consecutive nights/);}finally{f.close();}});

test('L5: arbitrator self-proxy is not allowed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);assert.throws(()=>f.manager.submitAction(f.code,arb.player_code,{targetCode:arb.player_code}),/Choose another player/);}finally{f.close();}});

test('L5: chirurgeon + arbitrator on same target → arbitrator dies first',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),arb=players[6],target=players[7],chirurgeon=players[3],murderer=players[0];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('arbitrator','loyalist',f.code,arb.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('murderer','heretic',f.code,murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('chirurgeon','loyalist',f.code,chirurgeon.player_code);f.manager.db.prepare('UPDATE hr_players SET faction=? WHERE game_code=? AND player_code=?').run('loyalist',f.code,target.player_code);f.manager.submitAction(f.code,arb.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arb.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'chirurgeon survived');}finally{f.close();}});

test('L5: no L3 regression — existing chirurgeon protect still works',()=>{const f=fixture();try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived via chirurgeon protect');assert.equal(f.manager.player(f.code,chirurgeon.player_code).drift,1,'chirurgeon paid drift');}finally{f.close();}});

function fixtureL4(randomFn,count=8){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-l4-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:randomFn});const{code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

function setupL4Target(f,targetDrift,skipTargetSleep=false){f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code),l4=players[6],target=players[7];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('novice-psychic','loyalist',f.code,l4.player_code);f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('imperial-citizen','loyalist',f.code,target.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=? WHERE game_code=? AND player_code=?').run(targetDrift,f.code,target.player_code);if(skipTargetSleep)f.manager.db.prepare('UPDATE hr_players SET skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);return{l4,target};}

test('L4: novice-psychic investigates a Green-zone target returns Green string',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const greenHint=f.manager.hints(f.code).green;assert.ok(msgs.some(m=>m.body===greenHint),'L4 received green hint');assert.equal(msgs.length,2,'L4 received role announcement + investigation result');const otherMsgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code!=?").all(f.code,l4.player_code);assert.ok(!otherMsgs.some(m=>m.body===greenHint),'No other player received the hint');}finally{f.close();}});

test('L4: novice-psychic investigating Yellow target — 100 rolls, noise rate ≈ 10%',()=>{let flips=0;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,6);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const yellowHint=f.manager.hints(f.code).yellow;if(msgs[1]?.body!==yellowHint)flips++;}finally{f.close();}}assert.ok(flips>=5&&flips<=15,`Expected ~10 flips, got ${flips}`);});

test('L4: novice-psychic investigating Orange target — 100 rolls, noise rate ≈ 20%',()=>{let flips=0;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,11);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const orangeHint=f.manager.hints(f.code).orange;if(msgs[1]?.body!==orangeHint)flips++;}finally{f.close();}}assert.ok(flips>=12&&flips<=28,`Expected ~20 flips, got ${flips}`);});

test('L4: novice-psychic investigating Black target — flips are always Red (only adjacent zone)',()=>{let flips=0,allRed=true;const ROLLS=100;for(let i=0;i<ROLLS;i++){const f=fixtureL4(()=>i/ROLLS);try{const{l4,target}=setupL4Target(f,20,true);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,l4.player_code);const blackHint=f.manager.hints(f.code).black;const redHint=f.manager.hints(f.code).red;const hint=msgs[1]?.body;if(hint!==blackHint){flips++;if(hint!==redHint)allRed=false;}}finally{f.close();}}assert.ok(flips>=40&&flips<=60,`Expected ~50 flips, got ${flips}`);assert.ok(allRed,'All noise flips returned Red (only adjacent zone to Black)');});

test('L4: crippled novice-psychic is silently rejected (no error, no drift)',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,l4.player_code);const result=f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});assert.equal(result.silent,true);assert.equal(result.kind,'drift-hint');assert.equal(f.manager.player(f.code,l4.player_code).drift,0,'crippled L4 paid no drift');}finally{f.close();}});

test('L4: novice-psychic self-investigate is rejected',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const l4=f.manager.players(f.code)[6];f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('novice-psychic','loyalist',f.code,l4.player_code);assert.throws(()=>f.manager.submitAction(f.code,l4.player_code,{targetCode:l4.player_code}),/Choose another player/);}finally{f.close();}});

test('L4: novice-psychic pays +1 drift when night action resolves',()=>{const f=fixture(8);try{const{l4,target}=setupL4Target(f,0);f.manager.submitAction(f.code,l4.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,l4.player_code).drift,1,'L4 paid +1 drift');}finally{f.close();}});

test('T1 cripple recovers after 1 round of no re-interrogation — night action works on next night',()=>{const f=fixture();try{f.manager.start(f.code,'p0');const chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),voters=f.manager.players(f.code).filter(p=>p.player_code!==chirurgeon.player_code).slice(0,2);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);for(const p of voters)f.manager.vote(f.code,p.player_code,chirurgeon.player_code);f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,chirurgeon.player_code).cripple_tier,1,'T1 applied');assert.equal(f.manager.player(f.code,chirurgeon.player_code).tier1_until_round,2,'tier1_until_round is current round');assert.equal(f.manager.player(f.code,chirurgeon.player_code).alive,1,'still alive');// Night 2: T1 active — action silently rejected
const target=f.manager.players(f.code).find(p=>p.player_code!==chirurgeon.player_code&&p.alive);
const night1Result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});
assert.equal(night1Result.silent,true,'T1 blocks action');
f.manager.resolve(f.code,true);
// Day 2: T1 should have cleared during night→day transition
assert.equal(f.manager.player(f.code,chirurgeon.player_code).cripple_tier,0,'T1 cleared');
assert.equal(f.manager.player(f.code,chirurgeon.player_code).tier1_until_round,null,'tier1_until_round cleared');
// Night 2: chirurgeon can act again
f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);
const result=f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});
assert.equal(result.silent,undefined,'action is not silently rejected');
assert.equal(result.kind,'protect','action kind is protect');
  }finally{f.close();}
});

test('L7: Psyker fires kill → target dies, Psyker at +15 drift',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code);f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'target died');assert.equal(f.manager.player(f.code,psyker.player_code).drift,16,'Psyker at +16 drift (+15 kill +1 witness)');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Psyker can kill a fellow Loyalist — not faction-locked like Murderer (loyalist-kit.md: "identical to Murderer" is a visibility claim, not a targeting one)',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==psyker.player_code);assert.doesNotThrow(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),'Psyker may target anyone, including a fellow Loyalist');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'the Loyalist target still dies — Psyker is a blunt instrument, not an intel role');}finally{f.close();}});

test('H1: Murderer still cannot target a fellow Heretic after the target-field fix (regression guard)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),fellowHeretic=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==murderer.player_code);assert.throws(()=>f.manager.submitAction(f.code,murderer.player_code,{targetCode:fellowHeretic.player_code}),/not hostile/);}finally{f.close();}});

test('L7: Chirurgeon protect on target → kill blocked, kill consumed, drift still applied',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,psyker.player_code).drift,15,'Psyker paid drift');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Arbitrator bodyguard redirects kill → Arbitrator dies, Psyker at +15 drift',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),arbitrator=f.manager.players(f.code).find(p=>p.role_id==='arbitrator'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code);f.manager.submitAction(f.code,arbitrator.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,arbitrator.player_code).alive,0,'arbitrator died');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,psyker.player_code).drift,16,'Psyker at +16 drift (+15 kill +1 witness)');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed');}finally{f.close();}});

test('L7: Saboteur trap on Psyker → +20 total drift (15+5), kill NOT consumed',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==psyker.player_code&&p.player_code!==saboteur.player_code);f.manager.submitAction(f.code,saboteur.player_code,{targetCode:psyker.player_code});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,psyker.player_code).drift,20,'Psyker at +20 drift');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived — kill blocked by actor trap');}finally{f.close();}});

test('L7: Execute on Sight — Interrogator T2 scan on Psyker at Red zone kills Psyker, kill NOT consumed',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),interrogator=f.manager.players(f.code).find(p=>p.role_id==='interrogator'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET drift=15 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,interrogator.player_code,{targetCode:psyker.player_code,variant:'T2'});f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,psyker.player_code).alive,0,'Psyker died from Execute on Sight');assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived — kill never fired');}finally{f.close();}});

test('Execute on Sight — Interrogator T2 scan on a Black-zone (20/20 drift) target kills them',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const interrogator=f.manager.players(f.code).find(p=>p.role_id==='interrogator'),target=f.manager.players(f.code).find(p=>p.player_code!==interrogator.player_code&&p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=20 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,interrogator.player_code,{targetCode:target.player_code,variant:'T2'});f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'Black zone (drift 20) is >=2 zone-upgrade, same threshold as Red — executes on T2+');assert.equal(after.drift,20,'drift is untouched by the execution itself');}finally{f.close();}});

test('Execute on Sight — a T1 (Soft) scan never kills, even against a Black-zone target',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const interrogator=f.manager.players(f.code).find(p=>p.role_id==='interrogator'),target=f.manager.players(f.code).find(p=>p.player_code!==interrogator.player_code&&p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=20 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,interrogator.player_code,{targetCode:target.player_code,variant:'T1'});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'T1 is the soft probe tier — execute-on-sight requires T2+ regardless of target zone');}finally{f.close();}});

test('T1 (Soft) scan result names the actual target, not a generic "Target"',()=>{const f=fixture(6);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const interrogator=f.manager.players(f.code).find(p=>p.role_id==='interrogator'),target=f.manager.players(f.code).find(p=>p.player_code!==interrogator.player_code&&p.faction==='loyalist');f.manager.submitAction(f.code,interrogator.player_code,{targetCode:target.player_code,variant:'T1'});f.manager.resolve(f.code,true);const msgs=f.manager.db.prepare("SELECT body FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=?").all(f.code,interrogator.player_code);assert.ok(msgs.some(m=>m.body===`${target.name} is clean.`||m.body===`${target.name} is tainted.`),'result names the target by name, e.g. "P1 is clean."');assert.ok(!msgs.some(m=>/^Target:/.test(m.body)),'no generic "Target:" phrasing left');}finally{f.close();}});

test('L7: T1 crippled Psyker cannot fire — recovers next night and kill works',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=1,tier1_until_round=1 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),0,'kill NOT consumed from blocked attempt');f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,psyker.player_code).cripple_tier,0,'T1 cleared');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'kill consumed after recovery');}finally{f.close();}});

test('L7: T2 crippled Psyker permanently blocked — T2 does not recover',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,psyker.player_code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);f.manager.advance(f.code,'p0');f.manager.advance(f.code,'p0');assert.equal(f.manager.player(f.code,psyker.player_code).cripple_tier,2,'T2 persists');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target.player_code}),/blocks this action/);}finally{f.close();}});

test('L7: killLimit honored — Psyker cannot fire a second time',()=>{const f=fixture(7);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const psyker=f.manager.players(f.code).find(p=>p.role_id==='sanctioned-psyker'),target1=f.manager.players(f.code).find(p=>p.faction==='heretic');f.manager.submitAction(f.code,psyker.player_code,{targetCode:target1.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.usage(f.code,psyker.player_code,'kill'),1,'first kill consumed');const target2=f.manager.players(f.code).find(p=>p.alive&&p.faction==='heretic'&&p.player_code!==target1.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,psyker.player_code,{targetCode:target2.player_code}),/once per game/);}finally{f.close();}});

test('L7: at 5p and 6p, Sanctioned Psyker is NOT in the composition',()=>{const f=fixture();try{const ids5=f.manager.presetFor(5);assert.equal(ids5.includes('sanctioned-psyker'),false,'Psyker not at 5p');const ids6=f.manager.presetFor(6);assert.equal(ids6.includes('sanctioned-psyker'),false,'Psyker not at 6p');}finally{f.close();}});

test('L7: at 7p, Sanctioned Psyker IS in the composition exactly once',()=>{const f=fixture();try{const ids7=f.manager.presetFor(7);assert.ok(ids7.includes('sanctioned-psyker'),'Psyker at 7p');assert.equal(ids7.filter(x=>x==='sanctioned-psyker').length,1,'exactly one Psyker');}finally{f.close();}});

function fixtureHereticPriest(count=8){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'heresy-hp-'));let now=1_000_000;const manager=new HeresyGameManager({databasePath:path.join(dir,'game.db'),now:()=>now,random:()=>0.9});const{code}=manager.create({playerCode:'p0',name:'P0'});for(let i=1;i<count;i++){manager.join({code,playerCode:`p${i}`,name:`P${i}`});manager.ready(code,`p${i}`,true);}return{manager,code,close(){manager.close();fs.rmSync(dir,{recursive:true,force:true});}};}

function setupHereticPriestGame(f){f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const players=f.manager.players(f.code);const hp=players.find(p=>p.role_id==='heretic-priest');if(!hp){const p=players.find(x=>x.faction==='heretic');f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('heretic-priest','heretic',f.code,p.player_code);}const priest=f.manager.players(f.code).find(p=>p.role_id==='heretic-priest');const target=f.manager.players(f.code).find(p=>p.player_code!==priest.player_code);return{priest,target};}

test('H2: Warp Litany against Green-zone target (drift 0) silently rejects',()=>{const f=fixtureHereticPriest();try{const{priest,target}=setupHereticPriestGame(f);f.manager.db.prepare('UPDATE hr_players SET drift=0,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result.silent,true,'action silently rejected');assert.equal(result.ok,false,'ok is false');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,priest.player_code).drift,0,'priest drift unchanged');assert.equal(f.manager.player(f.code,target.player_code).drift,0,'target drift unchanged');const privateMsgs=f.manager.db.prepare("SELECT * FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code IN (?,?)").all(f.code,priest.player_code,target.player_code);assert.ok(!privateMsgs.some(m=>/warp|litany/i.test(m.body)),'no notification to either party');const actions=f.manager.actions(f.code,f.manager.game(f.code).round);assert.equal(actions.length,0,'no action recorded');}finally{f.close();}});

test('H2: Warp Litany against Yellow-zone target (drift 9) silently rejects',()=>{const f=fixtureHereticPriest();try{const{priest,target}=setupHereticPriestGame(f);f.manager.db.prepare('UPDATE hr_players SET drift=9,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result.silent,true,'action silently rejected');assert.equal(result.ok,false,'ok is false');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,priest.player_code).drift,0,'priest drift unchanged');assert.equal(f.manager.player(f.code,target.player_code).drift,9,'target drift unchanged');const actions=f.manager.actions(f.code,f.manager.game(f.code).round);assert.equal(actions.length,0,'no action recorded');}finally{f.close();}});

test('H2: Warp Litany against Orange-zone target (drift 10) succeeds',()=>{const f=fixtureHereticPriest();try{const{priest,target}=setupHereticPriestGame(f);f.manager.db.prepare('UPDATE hr_players SET drift=10,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result.silent,undefined,'action not silently rejected');assert.equal(result.kind,'corrupt-sermon');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,priest.player_code).drift,4,'priest gains +4 drift');assert.equal(f.manager.player(f.code,target.player_code).drift,20,'target gains +12 drift (capped at max 20)');const usage=f.manager.usage(f.code,priest.player_code,'warp-litany');assert.equal(usage,1,'warp litany usage incremented');}finally{f.close();}});

test('H2: Warp Litany against Red-zone target (drift 15) succeeds',()=>{const f=fixtureHereticPriest();try{const{priest,target}=setupHereticPriestGame(f);f.manager.db.prepare('UPDATE hr_players SET drift=15,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result.silent,undefined,'action not silently rejected');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,priest.player_code).drift,4,'priest gains +4 drift');assert.equal(f.manager.player(f.code,target.player_code).drift,20,'target gains +12 drift (capped at max)');}finally{f.close();}});

test('H2: Warp Litany once-per-game enforced — silent reject does not consume the usage',()=>{const f=fixtureHereticPriest();try{const{priest,target}=setupHereticPriestGame(f);f.manager.db.prepare('UPDATE hr_players SET drift=0 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result1=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result1.silent,true,'first attempt silently rejected');assert.equal(result1.ok,false);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night',round=2 WHERE code=?").run(f.code);f.manager.db.prepare('UPDATE hr_players SET drift=10,skip_next_night=1 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);const result2=f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'});assert.equal(result2.silent,undefined,'second attempt succeeds');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,priest.player_code).drift,4,'priest gains +4 drift on successful use');const usage=f.manager.usage(f.code,priest.player_code,'warp-litany');assert.equal(usage,1,'usage count is 1 after successful use');f.manager.db.prepare("UPDATE hr_games SET phase='night',round=3 WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,priest.player_code,{targetCode:target.player_code,variant:'warp-litany'}),/limit/,'third attempt throws limit error');}finally{f.close();}});

// ── H1: Murderer drift-gated kill (heretic-kit.md v1.5.0) ──
// NOTE: the dispatch's own test table includes "Murderer at drift 5 (Yellow)
// attempts kill -> Gated" but 5+15=20 is NOT >MAX_DRIFT(20) per the gate's
// own stated formula (both docs agree: "if current_drift+15 > MAX_DRIFT").
// That example doesn't gate under the formula as written — using drift 6
// (21>20) here instead, which is the correct lowest-Yellow gating value.

test('H1: Murderer kills at drift 0 → succeeds, +16 drift (15 kill + 1 witness), target dies',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'target died');assert.equal(f.manager.player(f.code,murderer.player_code).drift,16,'Murderer at +16 (15 kill + 1 witness)');}finally{f.close();}});

test('H1: Murderer at drift 15 (Red) is gated — no drift charged, target +1, Red cue',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=15 WHERE game_code=? AND player_code=?').run(f.code,murderer.player_code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,15,'Murderer unchanged');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survived');assert.equal(f.manager.player(f.code,target.player_code).drift,1,'target felt watched (+1)');const state=f.manager.state(f.code,murderer.player_code);assert.match(state.privateMessages.at(-1).body,/Warp peels away your intent/,'Red-tone cue delivered privately');const event=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='night-action' ORDER BY id DESC LIMIT 1").get(f.code);assert.equal(JSON.parse(event.payload).kind,'murderer:kill-gated');}finally{f.close();}});

test('H1: Murderer at drift 6 (Yellow, lowest gating value) is gated — Yellow-tone cue',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=6 WHERE game_code=? AND player_code=?').run(f.code,murderer.player_code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,6,'gated — unchanged');const state=f.manager.state(f.code,murderer.player_code);assert.match(state.privateMessages.at(-1).body,/hesitation, a wrongness/,'Yellow-tone cue');}finally{f.close();}});

test('H1: Murderer at drift 13 (Orange) is gated — Orange-tone cue',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=13 WHERE game_code=? AND player_code=?').run(f.code,murderer.player_code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,13,'gated — unchanged');const state=f.manager.state(f.code,murderer.player_code);assert.match(state.privateMessages.at(-1).body,/hand is shaking/,'Orange-tone cue');}finally{f.close();}});

test('H1: gate fires before interrupts are evaluated — Chirurgeon protect not even reached',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code&&p.player_code!==chirurgeon.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=19 WHERE game_code=? AND player_code=?').run(f.code,murderer.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,19,'unchanged — gated (19+15=34>20)');assert.equal(f.manager.player(f.code,target.player_code).drift,1,'target only gets the gate tick, protect never evaluated');}finally{f.close();}});

test('H1: Priest Litany heals Murderer below the gate, enabling a later kill',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),priest=f.manager.players(f.code).find(p=>p.role_id==='priest'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.db.prepare('UPDATE hr_players SET drift=7 WHERE game_code=? AND player_code=?').run(f.code,murderer.player_code);f.manager.submitAction(f.code,priest.player_code,{targetCode:murderer.player_code,variant:'litany'});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,0,'Litany floored at 0 (7-10)');f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'kill succeeds from drift 0');assert.equal(f.manager.player(f.code,murderer.player_code).drift,16,'Murderer at +16 (15 kill + 1 witness)');}finally{f.close();}});

// ── Blood Ritual (blood-ritual.md v1.0.0), formerly "Sanctioned Violence" ──
// Renamed 2026-07-25 — "Sanctioned" read as a Loyalist-flavored word for a
// Heretic mechanic. Murderer is a valid attacker (reversed from the initial
// dispatch read); note they still only get one action per night — a kill and
// a Blood Ritual submission share the same hr_actions row, so taking one
// forgoes the other that night (see submitFactionAction's comment). No
// alignment reveal on kill, matching the spec's explicit "same as Murderer"
// statement (not the contradictory action-shape-table row implying a reveal).

test('Blood Ritual: fresh attack cripples the target one tier, no witness drift',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,saboteur.player_code).drift,3,'attacker paid +3');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1,'target crippled +1 tier');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'target survives night 1');assert.ok(f.manager.players(f.code).filter(p=>p.alive&&p.player_code!==saboteur.player_code).every(p=>p.drift===0),'no witness drift on a cripple night');}finally{f.close();}});

test('Blood Ritual: same target attacked the following night escalates to a kill',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,0,'target killed on the escalation night');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,3,'tier at MAX');assert.equal(f.manager.player(f.code,saboteur.player_code).drift,7,'3+3 attacker cost + 1 witness');const msgs=f.manager.historyMessages(f.code,'p0','public').messages;assert.ok(!msgs.some(m=>new RegExp(target.name+'.*(loyalist|heretic)').test(m.body)),'no alignment reveal on an SV kill');}finally{f.close();}});

test('Blood Ritual: different target the following night resets escalation (fresh cripple, no kill)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),targets=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:targets[0].player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:targets[1].player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,targets[1].player_code).cripple_tier,1,'fresh cripple, not escalated');assert.equal(f.manager.player(f.code,targets[1].player_code).alive,1);}finally{f.close();}});

test('Blood Ritual: skipping a night resets escalation — next attack on the same target is a fresh cripple',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).alive,1,'streak was broken by the skip — no kill');
  // Not tier 2: the skipped night gave the pre-existing T1-recovery rule (in
  // setPhase) a full cycle to heal the round-1 cripple back to 0 before this
  // fresh cripple landed — so it's a fresh 0->1, not a stacked 1->2.
  assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1,'fresh cripple from a healed baseline (0->1), not jumped to 3');}finally{f.close();}});

test('Blood Ritual: a second faction-wide submission the same night is rejected outright',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),hereticPriest=f.manager.players(f.code).find(p=>p.role_id==='heretic-priest'),targets=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:targets[0].player_code});assert.throws(()=>f.manager.submitFactionAction(f.code,hereticPriest.player_code,{targetCode:targets[1].player_code}),/already been claimed/);}finally{f.close();}});

test('Blood Ritual: a crippled Heretic cannot submit Blood Ritual',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET cripple_tier=2 WHERE game_code=? AND player_code=?').run(f.code,saboteur.player_code);assert.throws(()=>f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code}),/Interrogation damage blocks/);}finally{f.close();}});

test('Blood Ritual: targeting a fellow Heretic is rejected',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),fellowHeretic=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==saboteur.player_code);assert.throws(()=>f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:fellowHeretic.player_code}),/not hostile/);}finally{f.close();}});

test('Blood Ritual: the Murderer is a valid attacker for the cabal',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitFactionAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,3,'Murderer paid the Blood Ritual attacker cost, not the +15 kill cost');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1,'fresh cripple landed');}finally{f.close();}});

test('Blood Ritual: a Murderer who submits it that night forgoes their own kill (shared action slot)',()=>{const f=fixture(5);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const murderer=f.manager.players(f.code).find(p=>p.role_id==='murderer'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==murderer.player_code);f.manager.submitAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.submitFactionAction(f.code,murderer.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,murderer.player_code).drift,3,'only the Blood Ritual cost applied — the kill submission was overwritten');assert.equal(f.manager.player(f.code,target.player_code).alive,1,'no kill happened, only a cripple');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1);}finally{f.close();}});

test('Blood Ritual: a Loyalist cannot submit Blood Ritual',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const loyalist=f.manager.players(f.code).find(p=>p.faction==='loyalist'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==loyalist.player_code);assert.throws(()=>f.manager.submitFactionAction(f.code,loyalist.player_code,{targetCode:target.player_code}),/Only Heretics/);}finally{f.close();}});

test('Blood Ritual: Chirurgeon protect blocks the attack silently, attacker still pays',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==chirurgeon.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitFactionAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,0,'protected — no cripple landed');assert.equal(f.manager.player(f.code,saboteur.player_code).drift,3,'attacker still paid the cost');}finally{f.close();}});

test('Blood Ritual: Saboteur trap on the attack target adds +5 extra drift to the attacker',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');f.manager.advance(f.code,'p0');const hereticPriest=f.manager.players(f.code).find(p=>p.role_id==='heretic-priest'),saboteur=f.manager.players(f.code).find(p=>p.role_id==='saboteur'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.submitAction(f.code,saboteur.player_code,{targetCode:target.player_code});f.manager.submitFactionAction(f.code,hereticPriest.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,hereticPriest.player_code).drift,8,'3 attacker cost + 5 trap');assert.equal(f.manager.player(f.code,target.player_code).cripple_tier,1,'cripple still lands despite the trap-on-target');}finally{f.close();}});

// ── Animus (roles/animus.md v1.0.0) — one-shot speculative possession ──
// Animus ships custom-roster only (not in any locked preset), so every test
// below starts from fixture(8) and reassigns a loyalist slot to animus/heretic
// directly, matching the arbitrator-reassignment pattern used above (L5).

// Composition is assigned inside start(), so the role_id/faction swap must
// happen AFTER start() runs — reassigning before it gets clobbered.
// Convert an EXISTING Heretic (not the Murderer) to Animus, not a Loyalist —
// swapping a Loyalist's faction would shift the heretic/loyalist ratio and
// can trip the parity win check the instant start() finishes.
function makeAnimus(f){const candidate=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.role_id!=='murderer');f.manager.db.prepare('UPDATE hr_players SET role_id=?,faction=? WHERE game_code=? AND player_code=?').run('animus','heretic',f.code,candidate.player_code);return f.manager.player(f.code,candidate.player_code);}

test('Animus: a Red-zone guess (15-19) succeeds — target possessed, skips next night, no reveal yet',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=17 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.possessed_by,animus.player_code,'target is possessed');assert.equal(after.skip_next_night,1,'target skips their next night action');assert.equal(after.alive,1,'no kill yet — detonation is day-end, not night-end');assert.equal(after.possession_revealed,0,'not yet revealed');const state=f.manager.state(f.code,animus.player_code);assert.match(state.privateMessages.at(-1).body,/summoning takes hold/);}finally{f.close();}});

test('Animus: a wrong guess (outside Red) wastes silently — no possession, no error, no learned reason',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.possessed_by,null,'not possessed');assert.equal(after.skip_next_night,0);const state=f.manager.state(f.code,animus.player_code);assert.match(state.privateMessages.at(-1).body,/finds no purchase/);}finally{f.close();}});

test('Animus: Chirurgeon protecting a Red-zone target the same night blocks the possession itself, indistinguishable from a wrong guess',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),chirurgeon=f.manager.players(f.code).find(p=>p.role_id==='chirurgeon'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.role_id!=='chirurgeon');f.manager.db.prepare('UPDATE hr_players SET drift=17 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,chirurgeon.player_code,{targetCode:target.player_code});f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code});f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.possessed_by,null,'possession was blocked despite the target actually being Red');assert.equal(after.skip_next_night,0);const state=f.manager.state(f.code,animus.player_code);assert.match(state.privateMessages.at(-1).body,/finds no purchase/,'Animus sees the same failure message as a wrong guess, no tell that it was blocked');assert.equal(f.manager.player(f.code,animus.player_code).drift,3,'Animus still pays the +3 attempt cost even though the possession was blocked');}finally{f.close();}});

test('Animus: self-drift is charged exactly once, at submission, win or lose (no double-charge)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=5 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code});assert.equal(f.manager.player(f.code,animus.player_code).drift,3,'charged immediately on submission');f.manager.resolve(f.code,true);assert.equal(f.manager.player(f.code,animus.player_code).drift,3,'unchanged by resolution — not double-charged by the generic per-player loop');}finally{f.close();}});

test('Animus: targeting a fellow Heretic is rejected (faction-locked)',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),fellowHeretic=f.manager.players(f.code).find(p=>p.faction==='heretic'&&p.player_code!==animus.player_code);assert.throws(()=>f.manager.submitAction(f.code,animus.player_code,{targetCode:fellowHeretic.player_code}),/not hostile/);}finally{f.close();}});

test('Animus: a dead target is rejected outright',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(f.code,target.player_code);assert.throws(()=>f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code}),/Dead players cannot do that/);}finally{f.close();}});

test('Animus: an already-possessed target cannot be targeted again',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run('someone-else',f.code,target.player_code);assert.throws(()=>f.manager.submitAction(f.code,animus.player_code,{targetCode:target.player_code}),/already possessed/);}finally{f.close();}});

test('Animus: one-shot — a second attempt after a resolved possession is rejected',()=>{const f=fixture(8);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),targets=f.manager.players(f.code).filter(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET drift=17 WHERE game_code=? AND player_code=?').run(f.code,targets[0].player_code);f.manager.submitAction(f.code,animus.player_code,{targetCode:targets[0].player_code});f.manager.resolve(f.code,true);f.manager.db.prepare("UPDATE hr_games SET phase='night' WHERE code=?").run(f.code);assert.throws(()=>f.manager.submitAction(f.code,animus.player_code,{targetCode:targets[1].player_code}),/one possession per game/);}finally{f.close();}});

test('Animus: possessed player\'s vote is silently suppressed from the tally',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),possessed=f.manager.players(f.code).find(p=>p.faction==='loyalist'),lynchTarget=f.manager.players(f.code).find(p=>p.faction==='loyalist'&&p.player_code!==possessed.player_code);f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run(animus.player_code,f.code,possessed.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);const others=f.manager.players(f.code).filter(p=>p.player_code!==possessed.player_code&&p.player_code!==lynchTarget.player_code&&p.alive);// Cast the possessed player's own vote for someone who should NOT win the tally if it counted
f.manager.vote(f.code,possessed.player_code,others[0].player_code);for(const p of others)f.manager.vote(f.code,p.player_code,lynchTarget.player_code);f.manager.resolve(f.code,true);const event=JSON.parse(f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(f.code).payload);assert.equal(event.target,lynchTarget.player_code,'possessed vote for the other candidate never counted');assert.equal(event.voterResults.some(r=>r.voter===possessed.player_code),false,'possessed voter excluded entirely from the tally');}finally{f.close();}});

test('Animus: day-end detonation kills the possessed target, reveals full role/faction/drift to everyone, excludes Animus from witness drift',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run(animus.player_code,f.code,target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);const voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code&&p.alive).slice(0,3);for(const p of voters)f.manager.vote(f.code,p.player_code,'skip');f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'detonated');assert.equal(after.possession_revealed,1);assert.equal(after.drift,0);const bystander=f.manager.players(f.code).find(p=>p.player_code!==animus.player_code&&p.player_code!==target.player_code);const bystanderState=f.manager.state(f.code,bystander.player_code);const revealed=bystanderState.players.find(p=>p.playerCode===target.player_code);assert.ok(revealed.role,'role revealed to a third party');assert.equal(revealed.faction,'loyalist');assert.equal(revealed.possessed,true);assert.equal(f.manager.player(f.code,bystander.player_code).drift,1,'bystander gets witnessed-violence drift');assert.equal(f.manager.player(f.code,animus.player_code).drift,0,'Animus itself is excluded from witnessed-violence drift');const events=f.manager.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='drift' ORDER BY id DESC LIMIT 5").all(f.code).map(e=>JSON.parse(e.payload));assert.equal(events.some(e=>e.playerCode===animus.player_code&&e.reason==='witnessed-violence'),false);}finally{f.close();}});

test('Animus: E1 — target lynched the same day the possession resolves still gets the fuller Neverborn reveal',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run(animus.player_code,f.code,target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);const voters=f.manager.players(f.code).filter(p=>p.player_code!==target.player_code&&p.alive).slice(0,3);for(const p of voters)f.manager.vote(f.code,p.player_code,target.player_code);f.manager.resolve(f.code,true);const after=f.manager.player(f.code,target.player_code);assert.equal(after.alive,0,'lynched');assert.equal(after.possession_revealed,1,'detonation still ran on the already-dead body');const msgs=f.manager.historyMessages(f.code,'p0','public').messages;assert.ok(msgs.some(m=>/body ruptures/.test(m.body)),'the fuller Neverborn reveal fired despite the lynch already killing the target');}finally{f.close();}});

test('Animus: possessed player cannot speak in public chat, but can speak-as the possessed target via sendMessageAs',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),target=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run(animus.player_code,f.code,target.player_code);f.manager.db.prepare("UPDATE hr_games SET phase='day',round=2,day_stage='vote' WHERE code=?").run(f.code);assert.throws(()=>f.manager.sendMessage(f.code,target.player_code,'public','I am innocent'),/possessed/);const message=f.manager.sendMessageAs(f.code,animus.player_code,'Trust me.');assert.equal(message.author,target.name,'message is attributed to the possessed target, not the Animus');}finally{f.close();}});

test('Animus: game-end reveal marks possessed:true ONLY for players who were actually possessed, not the whole roster',()=>{const f=fixture(9);try{f.manager.start(f.code,'p0');makeAnimus(f);f.manager.advance(f.code,'p0');const animus=f.manager.players(f.code).find(p=>p.role_id==='animus'),possessedTarget=f.manager.players(f.code).find(p=>p.faction==='loyalist');f.manager.db.prepare('UPDATE hr_players SET possessed_by=? WHERE game_code=? AND player_code=?').run(animus.player_code,f.code,possessedTarget.player_code);f.manager.db.prepare("UPDATE hr_games SET status='ended' WHERE code=?").run(f.code);const viewer=f.manager.players(f.code).find(p=>p.player_code!==animus.player_code&&p.player_code!==possessedTarget.player_code);const state=f.manager.state(f.code,viewer.player_code);const possessedRows=state.players.filter(p=>p.possessed);assert.deepEqual(possessedRows.map(p=>p.playerCode),[possessedTarget.player_code],'only the actually-possessed player is flagged, not every player in the ended game');const spectateState=f.manager.spectate(f.code);const spectatePossessedRows=spectateState.players.filter(p=>p.possessed);assert.deepEqual(spectatePossessedRows.map(p=>p.playerCode),[possessedTarget.player_code],'same guarantee for spectators');}finally{f.close();}});

