// exportTest()'s hard requirement (per its own file header) is that the
// generated file actually runs green under `node --test` — not just that it
// contains syntactically plausible JavaScript. This test generates a file
// from a resolved kill-chain board and then genuinely spawns `node --test`
// on it, asserting a clean exit.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createSandbox } from '../sandbox.js';
import { captureResolution } from '../trace.js';
import { exportTest } from '../exportTest.js';
import { buildKillChainSandbox } from './helpers.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const EXPORTS_DIR = path.join(__dirname, '..', '..', 'exports');

function cleanupExport(name) {
  try { fs.unlinkSync(path.join(EXPORTS_DIR, `${name}.test.js`)); } catch { /* already gone */ }
}

// This suite itself runs under `node --test`, which stamps NODE_TEST_CONTEXT
// / NODE_TEST_WORKER_ID into process.env for its own child-worker bookkeeping.
// spawnSync inherits process.env by default, and a `node --test` child that
// sees those already set treats itself as a nested worker and silently skips
// running any files ("run() is being called recursively... skipping running
// files") — so the child env here must have them stripped, or this test
// would "pass" without the generated file ever actually running.
function childEnv() {
  const env = { ...process.env };
  delete env.NODE_TEST_CONTEXT;
  delete env.NODE_TEST_WORKER_ID;
  return env;
}

test('export-test round-trip: generated file is syntactically valid and actually runs green under node --test', () => {
  const exportName = 'export_roundtrip_clean_kill';
  cleanupExport(exportName);

  const { sandbox, psyker, c1 } = buildKillChainSandbox(createSandbox, { seed: 401 });
  let generatedPath;
  try {
    sandbox.forcePhase('night', 1, null);
    sandbox.manager.submitAction(sandbox.code, psyker, { targetCode: c1 });
    const trace = captureResolution(sandbox.manager, sandbox.code, { rngRecorder: sandbox.rng });
    assert.equal(trace.integrity.ok, true, 'precondition: the captured trace is itself trustworthy');

    const result = exportTest({
      sandbox,
      trace,
      name: exportName,
      description: 'Generated by export-test-roundtrip.test.js — safe to delete.',
    });
    generatedPath = result.path;

    assert.equal(generatedPath, path.join(EXPORTS_DIR, `${exportName}.test.js`), 'writes to playground/exports/, never heresy-server/test/');
    assert.ok(fs.existsSync(generatedPath));
    assert.equal(fs.readFileSync(generatedPath, 'utf-8'), result.source, 'the returned source is exactly what was written to disk');

    // Syntax check first, for a clearer failure than the runtime one below
    // if this ever regresses.
    const syntaxCheck = spawnSync(process.execPath, ['--check', generatedPath], { encoding: 'utf-8', env: childEnv() });
    assert.equal(syntaxCheck.status, 0, `generated file has valid syntax:\n${syntaxCheck.stderr}`);

    // The real bar: run it.
    const run = spawnSync(process.execPath, ['--test', generatedPath], { encoding: 'utf-8', env: childEnv() });
    assert.equal(run.status, 0, `generated test exits 0 under node --test:\n${run.stdout}\n${run.stderr}`);
    assert.match(run.stdout + run.stderr, /\bpass 1\b/, 'exactly the one generated test ran and passed');
    assert.doesNotMatch(run.stdout + run.stderr, /\bfail [1-9]/, 'no failures');
  } finally {
    sandbox.close();
    if (generatedPath) cleanupExport(exportName);
  }
});

test('export-test: names/justifications with quotes, backslashes and newlines survive round-trip without corrupting the generated source', () => {
  const exportName = 'export_roundtrip_escaping';
  cleanupExport(exportName);

  const roster = ['murderer', 'chirurgeon', 'arbitrator', 'saboteur', 'imperial-citizen', 'imperial-citizen', 'imperial-citizen', 'imperial-citizen'];
  const players = [
    { name: 'Quote"Person' },
    { name: 'Back\\Slash' },
    { name: 'C2' }, { name: 'C3' }, { name: 'C4' }, { name: 'C5' }, { name: 'C6' }, { name: 'C7' },
  ];
  const sandbox = createSandbox({ players, roster, seed: 402, options: { maxDrift: 20 } });
  let generatedPath;
  try {
    const [murd, chir, arb, sab, c2, c3, c4, c5] = sandbox.listPlayerCodes().map(p => p.playerCode);
    sandbox.forcePhase('day', 2, 'vote');
    sandbox.manager.vote(sandbox.code, murd, c2, 'She said "trust no one" — then vanished.\nSecond line, with a \\backslash.');

    const result = exportTest({
      sandbox,
      name: exportName,
      description: 'quotes "in" description\nand a second line\\with a backslash',
    });
    generatedPath = result.path;

    const syntaxCheck = spawnSync(process.execPath, ['--check', generatedPath], { encoding: 'utf-8', env: childEnv() });
    assert.equal(syntaxCheck.status, 0, `generated file has valid syntax despite adversarial strings:\n${syntaxCheck.stderr}`);

    const run = spawnSync(process.execPath, ['--test', generatedPath], { encoding: 'utf-8', env: childEnv() });
    assert.equal(run.status, 0, `generated test exits 0:\n${run.stdout}\n${run.stderr}`);
  } finally {
    sandbox.close();
    if (generatedPath) cleanupExport(exportName);
  }
});
