import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { generateRoomCode, sanitizePlayerName, shuffle } from './utils.js';
import { loadGameConfig } from './gameConfig.js';
import { driftZone, intelNoiseRate, noisyResult } from './mechanics/drift.js';
import { effectiveCrippleTier, getEffectiveScanTier, isExecuteOnSight } from './mechanics/interrogation.js';

const schema = `
CREATE TABLE IF NOT EXISTS hr_games(code TEXT PRIMARY KEY,host_code TEXT NOT NULL,mode TEXT NOT NULL,phase TEXT NOT NULL DEFAULT 'lobby',day_stage TEXT,status TEXT NOT NULL DEFAULT 'lobby',round INTEGER NOT NULL DEFAULT 0,deadline INTEGER,day_ms INTEGER NOT NULL,night_ms INTEGER NOT NULL,max_drift INTEGER NOT NULL,hint_profile TEXT NOT NULL DEFAULT 'default',last_interrogated_target TEXT,last_interrogation_tier INTEGER NOT NULL DEFAULT 0,winner TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS hr_players(game_code TEXT NOT NULL,player_code TEXT NOT NULL,name TEXT NOT NULL,seat INTEGER NOT NULL,role_id TEXT,faction TEXT,drift INTEGER NOT NULL DEFAULT 0,alive INTEGER NOT NULL DEFAULT 1,ready INTEGER NOT NULL DEFAULT 0,connected INTEGER NOT NULL DEFAULT 1,cripple_tier INTEGER NOT NULL DEFAULT 0,tier1_until_round INTEGER,confessed INTEGER NOT NULL DEFAULT 0,confession_token_round INTEGER,skip_next_night INTEGER NOT NULL DEFAULT 0,joined_at INTEGER NOT NULL,PRIMARY KEY(game_code,player_code));
CREATE TABLE IF NOT EXISTS hr_actions(game_code TEXT NOT NULL,round INTEGER NOT NULL,actor_code TEXT NOT NULL,kind TEXT NOT NULL,target_code TEXT,variant TEXT,data TEXT,created_at INTEGER NOT NULL,PRIMARY KEY(game_code,round,actor_code));
CREATE TABLE IF NOT EXISTS hr_votes(game_code TEXT NOT NULL,round INTEGER NOT NULL,stage TEXT NOT NULL,voter_code TEXT NOT NULL,choice TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(game_code,round,stage,voter_code));
CREATE TABLE IF NOT EXISTS hr_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,game_code TEXT NOT NULL,channel TEXT NOT NULL,recipient_code TEXT,player_code TEXT,author TEXT NOT NULL,body TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'player',created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS hr_messages_cursor ON hr_messages(game_code,id);
CREATE TABLE IF NOT EXISTS hr_usage(game_code TEXT NOT NULL,player_code TEXT NOT NULL,ability TEXT NOT NULL,uses INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(game_code,player_code,ability));
CREATE TABLE IF NOT EXISTS hr_events(id INTEGER PRIMARY KEY AUTOINCREMENT,game_code TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL);
`;

export function isHostileTo(a, b) {
  // TODO(heresy-spec): v1 hostility is the non-canonical two-faction inequality default.
  return a.faction !== b.faction;
}

export class HeresyGameManager {
  constructor({ databasePath = process.env.GAME_DB_PATH || path.join(process.cwd(), 'data', 'heresy-rising.db'), now = () => Date.now(), random = Math.random } = {}) {
    fs.mkdirSync(path.dirname(databasePath), { recursive: true });
    this.db = new Database(databasePath); this.db.pragma('journal_mode = WAL'); this.db.exec(schema);this.ensureColumn('hr_games','hint_profile',"TEXT NOT NULL DEFAULT 'default'");
    this.now = now; this.random = random; this.config = loadGameConfig();
  }
  close(){this.db.close();}
  ensureColumn(table,column,definition){if(!this.db.prepare(`PRAGMA table_info(${table})`).all().some(x=>x.name===column))this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);}
  game(c){return this.db.prepare('SELECT * FROM hr_games WHERE code=?').get(c);}
  players(c){return this.db.prepare('SELECT * FROM hr_players WHERE game_code=? ORDER BY seat').all(c);}
  player(c,p){return this.db.prepare('SELECT * FROM hr_players WHERE game_code=? AND player_code=?').get(c,p);}
  role(id){const role=this.config.roles.get(id);if(!role)throw new Error('Unknown role data');return role;}
  codes(){return new Set(this.db.prepare('SELECT code FROM hr_games').all().map(x=>x.code));}
  presetFor(count){
    // TODO(heresy-spec): Entire 5–12 composition table and priority fallback are non-canonical, unplaytested defaults.
    const exact=this.config.composition[String(count)]; if(exact)return [...exact];
    const roles=this.config.composition.fallbackPriority.slice(0,Math.max(0,count-1));
    while(roles.length<count)roles.push('imperial-citizen'); return roles.slice(0,count);
  }
  roleDefinitions(){return this.config.roleList.map(({ability,objective,...role})=>({...role,ability,objective}));}
  create({playerCode,name,mode='live',options={}}){
    if(!playerCode)throw new Error('playerCode is required'); if(!['live','async'].includes(mode))throw new Error('Invalid game mode');
    const code=generateRoomCode(this.codes(),6),now=this.now(),dayMs=Number(options.dayMs)||(mode==='async'?86400000:300000),nightMs=Number(options.nightMs)||(mode==='async'?43200000:120000),max=Math.max(1,Number(options.maxDrift)||this.config.drift.MAX_DRIFT),hintProfile=this.config.hintProfiles[options.hintProfile] ? options.hintProfile : 'default';
    this.db.prepare('INSERT INTO hr_games(code,host_code,mode,day_ms,night_ms,max_drift,hint_profile,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(code,playerCode,mode,dayMs,nightMs,max,hintProfile,now,now);
    this.db.prepare('INSERT INTO hr_players(game_code,player_code,name,seat,joined_at) VALUES(?,?,?,?,?)').run(code,playerCode,sanitizePlayerName(name),0,now); return {code,state:this.state(code,playerCode)};
  }
  join({code,playerCode,name}){const g=this.requireGame(code);let p=this.player(code,playerCode);if(!p){if(g.phase!=='lobby')throw new Error('Game already started');const count=this.players(code).length;if(count>=12)throw new Error('Game is full');this.db.prepare('INSERT INTO hr_players(game_code,player_code,name,seat,joined_at) VALUES(?,?,?,?,?)').run(code,playerCode,sanitizePlayerName(name),count,this.now());}else this.db.prepare('UPDATE hr_players SET connected=1 WHERE game_code=? AND player_code=?').run(code,playerCode);return this.state(code,playerCode);}
  disconnect(playerCode){this.db.prepare('UPDATE hr_players SET connected=0 WHERE player_code=?').run(playerCode);}
  ready(c,p,value){this.requirePlayer(c,p);this.db.prepare('UPDATE hr_players SET ready=? WHERE game_code=? AND player_code=?').run(value===undefined?1:+!!value,c,p);return this.state(c,p);}
  start(c,p,{maxDrift}={}){const g=this.requireHost(c,p),players=this.players(c);if(g.phase!=='lobby')throw new Error('Already started');if(players.length<5||players.length>12)throw new Error('Games require 5–12 players');if(players.some(x=>x.player_code!==p&&!x.ready))throw new Error('All players must be ready');const ids=this.presetFor(players.length);if(ids.length!==players.length)throw new Error('Invalid composition');ids.filter(x=>x!=='imperial-citizen').forEach((id,i,a)=>{if(a.indexOf(id)!==i)throw new Error('Non-Citizen roles must be unique');});const assigned=shuffle(ids);this.db.transaction(()=>{players.forEach((x,i)=>{const r=this.role(assigned[i]);this.db.prepare('UPDATE hr_players SET role_id=?,faction=?,drift=0,alive=1,cripple_tier=0,confessed=0 WHERE game_code=? AND player_code=?').run(r.id,r.faction,c,x.player_code);});this.db.prepare("UPDATE hr_games SET phase='role-reveal',status='active',round=0,max_drift=?,deadline=NULL,updated_at=? WHERE code=?").run(Math.max(1,Number(maxDrift)||g.max_drift),this.now(),c);this.system(c,'Roles assigned. Review your private dossier.');})();return this.state(c,p);}
  advance(c,p){this.requireHost(c,p);return this.resolve(c,true);}
  resolve(c,force=false){const g=this.requireGame(c);if(g.status!=='active')throw new Error('Game is not active');if(!force&&g.deadline&&g.deadline>this.now())throw new Error('Phase is active');if(g.phase==='role-reveal')this.setPhase(c,'night',1);else if(g.phase==='night')this.resolveNight(g);else if(g.phase==='day')this.resolveDay(g);return this.game(c);}
  setPhase(c,phase,round,dayStage=null){const g=this.game(c),duration=phase==='night'?g.night_ms:g.day_ms,deadline=this.now()+duration,stage=phase==='day'?(dayStage||'vote'):dayStage;this.db.prepare('UPDATE hr_games SET phase=?,round=?,day_stage=?,deadline=?,updated_at=? WHERE code=?').run(phase,round,stage,deadline,this.now(),c);if(phase==='night')this.db.prepare('UPDATE hr_players SET confession_token_round=NULL WHERE game_code=?').run(c);if(phase==='day')this.db.prepare('UPDATE hr_players SET cripple_tier=0,tier1_until_round=NULL WHERE game_code=? AND cripple_tier=1 AND tier1_until_round<?').run(c,round);this.system(c,phase==='day'?`Day ${round}: vote for a target or stand down.`:`Night ${round} has begun.`);}
  resolveNight(g){const c=g.code,players=this.players(c).filter(p=>p.alive),actions=this.actions(c,g.round),traps=new Map(actions.filter(a=>a.kind==='boobytrap').map(a=>[a.target_code,a]));const protectedIds=new Set(),bodyguards=new Map();
    for(const p of players){const a=actions.find(x=>x.actor_code===p.player_code),role=this.role(p.role_id);if(p.skip_next_night){this.db.prepare('UPDATE hr_players SET skip_next_night=0 WHERE game_code=? AND player_code=?').run(c,p.player_code);continue;}if(!a){this.changeDrift(c,p.player_code,this.config.drift.NIGHTLY_SLEEP_RECOVERY,'sleep');continue;}this.changeDrift(c,p.player_code,role.driftWeight,'night-action');}
    for(const a of actions.filter(x=>x.kind==='protect'))if(!this.trapBlocks(c,g,a,traps))protectedIds.add(a.target_code);
    for(const a of actions.filter(x=>x.kind==='bodyguard'))if(!this.trapBlocks(c,g,a,traps))bodyguards.set(a.target_code,a.actor_code);
    for(const a of actions.filter(x=>['sermon','corrupt-sermon'].includes(x.kind))){if(this.trapBlocks(c,g,a,traps))continue;const s=this.config.drift.sermons[a.variant];this.changeDrift(c,a.actor_code,s.self,'sermon-self');this.changeDrift(c,a.target_code,s.target,'sermon-target');this.incrementUsage(c,a.actor_code,a.variant);}
    const autoKills=[];for(const a of actions.filter(x=>['investigate','drift-hint'].includes(x.kind))){if(this.trapBlocks(c,g,a,traps))continue;const result=this.resolveIntel(c,a);if(result?.autoKill)autoKills.push(result);}for(const k of autoKills){const victim=this.player(c,k.targetCode);if(!victim?.alive)continue;this.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(c,k.targetCode);this.system(c,`${victim.name} was executed by Interrogator. Confirmed warp-touched.`);this.system(c,`${victim.name}'s alignment: ${victim.faction}.`);for(const w of players)this.changeDrift(c,w.player_code,this.config.drift.WITNESSED_VIOLENCE,'witnessed-violence');}
    for(const a of actions.filter(x=>x.kind==='heretical-catalyst')){const target=this.player(c,a.target_code);if(traps.has(a.target_code))this.changeDrift(c,a.actor_code,this.config.drift.TRAP_DRIFT,'trap');if(target?.drift>=g.max_drift){this.db.prepare("UPDATE hr_players SET faction='heretic' WHERE game_code=? AND player_code=?").run(c,a.target_code);this.privateSystem(c,a.target_code,'The catalyst takes hold. Your loyalty has burned away.');}}
    const kill=actions.find(x=>x.kind==='kill');if(kill){if(traps.has(kill.target_code))this.changeDrift(c,kill.actor_code,this.config.drift.TRAP_DRIFT,'trap');let victim=kill.target_code;if(bodyguards.has(victim)){const guard=this.player(c,bodyguards.get(victim));this.privateSystem(c,guard.player_code,'You absorbed a strike meant for your proxy.');this.system(c,`${guard.name} absorbed a night strike and survived.`);victim=null;}if(protectedIds.has(kill.target_code))victim=null;if(victim){this.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(c,victim);this.system(c,`${this.player(c,victim).name} was slain in the night.`);for(const witness of this.players(c).filter(x=>x.alive))this.changeDrift(c,witness.player_code,this.config.drift.WITNESSED_VIOLENCE,'witnessed-violence');}}
    if(!this.finishIfWon(c))this.setPhase(c,'day',g.round,'vote');}
  trapBlocks(c,g,a,traps){if(!traps.has(a.target_code))return false;this.changeDrift(c,a.actor_code,this.config.drift.TRAP_DRIFT,'trap');const trap=traps.get(a.target_code);this.privateSystem(c,trap.actor_code,`Your trap caught ${this.player(c,a.actor_code).name} targeting ${this.player(c,a.target_code).name}.`);return !['kill','heretical-catalyst'].includes(a.kind);}
  resolveIntel(c,a){const actor=this.player(c,a.actor_code),target=this.player(c,a.target_code),role=this.role(actor.role_id);if(a.kind==='drift-hint'){let rate=intelNoiseRate(this.config.drift,actor.drift,role.driftWeight);const truth=driftZone(this.config.drift,target.drift).id;const zones=this.config.drift.zones;let shown=truth;if(this.random()<rate)shown=zones[Math.floor(this.random()*zones.length)].id;this.privateSystem(c,a.actor_code,this.hints(c)[shown]);return{};}const intensity=Number(String(a.variant||'T1').replace('T',''))||1;const targetZone=driftZone(this.config.drift,target.drift);if(isExecuteOnSight(intensity,targetZone.id))return{autoKill:true,targetCode:a.target_code};const effectiveTier=getEffectiveScanTier(intensity,targetZone.id);const rate=intelNoiseRate(this.config.drift,actor.drift,role.driftWeight);if(effectiveTier>=3){const text=target.faction==='loyalist'?'Confirmed: they are a Loyalist. The Emperor\'s light is unbroken in them.':'Confirmed: they are a Heretic. The warp taint is undeniable.';this.privateSystem(c,a.actor_code,text);return{};}const truth=target.faction==='loyalist';const result=noisyResult(truth,rate,this.random);let text=result==='unclear'?'You learned nothing.':result?'Their story holds together.':'Something does not add up.';if(effectiveTier>=2)text+=` You sense their drift zone: ${targetZone.id}.`;this.privateSystem(c,a.actor_code,text);return{};}
  resolveDay(g){if(g.day_stage==='response')throw new Error('Awaiting interrogation response or direct ask');this.resolveDayVote(g);}
  dayVotes(c,r){return this.db.prepare("SELECT * FROM hr_votes WHERE game_code=? AND round=? AND stage='target'").all(c,r);}
  resolveDayVote(g){const c=g.code,living=this.players(c).filter(p=>p.alive),votes=this.dayVotes(c,g.round),skipCount=votes.filter(v=>v.choice==='skip').length,threshold=living.length/2;if(skipCount>threshold)return this.skipDay(g,'skip-majority');const counts=new Map();for(const v of votes){if(v.choice==='skip')continue;const target=this.player(c,v.choice);if(target?.alive)counts.set(v.choice,(counts.get(v.choice)||0)+1);}const top=Math.max(0,...counts.values());if(top<=threshold)return this.skipDay(g,'threshold-not-met');let leaders=[...counts].filter(([,count])=>count===top).map(([code])=>code);if(leaders.length>1){const maxDrift=Math.max(...leaders.map(code=>this.player(c,code)?.drift??-1));leaders=leaders.filter(code=>(this.player(c,code)?.drift??-1)===maxDrift);if(leaders.length!==1)return this.skipDay(g,'tied-drift');}const targetCode=leaders[0],previous=this.previousDayResolution(c,g.round),samePrevious=previous?.outcome==='interrogate'&&previous.target===targetCode&&this.player(c,targetCode)?.alive,outcome=samePrevious?'lynch':'interrogate';return outcome==='lynch'?this.applyLynch(g,targetCode):this.applyInterrogation(g,targetCode);}
  previousDayResolution(c,round){const row=this.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(c);if(!row)return null;try{const payload=JSON.parse(row.payload);return payload.round===round-1?payload:null;}catch{return null;}}
  skipDay(g,reason='skip'){const c=g.code,payload={round:g.round,outcome:'skip',target:null,reason,voterResults:this.dayVotes(c,g.round).map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0})),witnessedDrift:0,alignmentRevealed:null,crippleTier:null};this.event(c,'day-resolution',payload);this.system(c,'The conclave stands down. No sentence is passed.');this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round+1);return payload;}
  applyInterrogation(g,targetCode){const c=g.code,target=this.player(c,targetCode);if(!target?.alive)return this.skipDay(g,'invalid-target');if(target.cripple_tier>=3)return this.skipDay(g,'target-already-crippled');const tier=Math.min(3,(Number(target.cripple_tier)||0)+1),voters=this.dayVotes(c,g.round).filter(v=>v.choice===targetCode);this.db.prepare('UPDATE hr_games SET last_interrogated_target=?,last_interrogation_tier=?,day_stage=?,deadline=NULL,updated_at=? WHERE code=?').run(targetCode,tier,null,this.now(),c);this.db.prepare('UPDATE hr_players SET cripple_tier=?,tier1_until_round=? WHERE game_code=? AND player_code=?').run(tier,tier===1?g.round+1:null,c,targetCode);const voterResults=voters.map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0}));let witnessedDrift=0;if(target.faction==='loyalist'){for(const result of voterResults){result.driftDelta=1;this.changeDrift(c,result.voter,1,'wrong-interrogation');}}else if(target.faction==='heretic'){witnessedDrift=-1;for(const p of this.players(c).filter(x=>x.alive))this.changeDrift(c,p.player_code,-1,'right-interrogation-cleansing');}const payload={round:g.round,outcome:'interrogate',target:targetCode,voterResults,witnessedDrift,alignmentRevealed:null,crippleTier:tier};this.event(c,'day-resolution',payload);this.system(c,`${target.name} was interrogated and left at Tier ${tier}.`);this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round+1);return payload;}
  applyLynch(g,targetCode){const c=g.code,target=this.player(c,targetCode),votes=this.dayVotes(c,g.round).filter(v=>v.choice===targetCode),voterResults=votes.map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0}));this.db.prepare('UPDATE hr_players SET cripple_tier=3,alive=0 WHERE game_code=? AND player_code=?').run(c,targetCode);this.system(c,`${target.name} was lynched and revealed ${target.faction}.`);for(const p of this.players(c).filter(x=>x.alive))this.changeDrift(c,p.player_code,1,'witnessed-violence');if(target.faction==='loyalist')for(const result of voterResults){result.driftDelta=this.config.drift.WRONG_LYNCH;this.changeDrift(c,result.voter,this.config.drift.WRONG_LYNCH,'wrong-lynch');}const payload={round:g.round,outcome:'lynch',target:targetCode,voterResults,witnessedDrift:1,alignmentRevealed:target.faction,crippleTier:3};this.event(c,'day-resolution',payload);this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round+1);return payload;}
  respondInterrogation(c,p,response){const g=this.requireGame(c),target=this.player(c,p);if(g.phase!=='day'||g.day_stage!=='response'||g.last_interrogated_target!==p)throw new Error('No response is pending');if(target.cripple_tier>=3)throw new Error('Tier 3 requires a direct ask');if(!['confess','resist','refuse-break'].includes(response))throw new Error('Invalid response');if(response==='confess'){
      // TODO(heresy-spec): Confession token blocks same-day re-interrogation, expires Day→Night, does not stack, and skips the next night action.
      this.db.prepare('UPDATE hr_players SET confessed=1,confession_token_round=?,skip_next_night=1 WHERE game_code=? AND player_code=?').run(g.round,c,p);this.system(c,`${target.name} confessed: ${this.role(target.role_id).displayName}.`);}else if(response==='resist')this.changeDrift(c,p,1,'resist');else{this.db.prepare('UPDATE hr_players SET cripple_tier=MAX(cripple_tier,2),skip_next_night=1 WHERE game_code=? AND player_code=?').run(c,p);this.changeDrift(c,p,2,'refuse-break');}this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round+1);return this.state(c,p);}
  askConfession(c,asker,targetCode){const g=this.requireGame(c);this.requireAlive(c,asker);const target=this.requirePlayer(c,targetCode);if(g.phase!=='day'||g.day_stage!=='response'||targetCode!==g.last_interrogated_target||target.cripple_tier<3)throw new Error('This player cannot be asked now');
    // TODO(heresy-spec): Tier 3 confession occurs only on a direct ask and is required for Loyalist victory.
    this.db.prepare('UPDATE hr_players SET confessed=1 WHERE game_code=? AND player_code=?').run(c,targetCode);this.system(c,`${target.name} is forced to confess: ${this.role(target.role_id).displayName}.`);this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round+1);return this.state(c,asker);}
  applyHereticCap(c,day){if(day!==this.config.drift.HERETIC_CAP_DAY)return;for(const p of this.players(c).filter(x=>x.alive&&x.faction==='heretic'&&x.drift<this.config.drift.HERETIC_DRIFT_CAP))this.changeDrift(c,p.player_code,this.config.drift.HERETIC_CAP_SPIKE,'heretic-cap');}
  vote(c,p,choice,justification=''){const g=this.requireGame(c),v=this.requireAlive(c,p),cleanChoice=String(choice||'');if(g.phase!=='day'||g.day_stage==='response')throw new Error('Voting is closed');if(cleanChoice!=='skip')this.requireAlive(c,cleanChoice);if(effectiveCrippleTier(v,g.round)>=2&&!String(justification).trim())throw new Error('Broken players must justify every vote');if(justification)this.insertMessage(c,'public',null,p,v.name,`Vote justification: ${String(justification).trim().slice(0,300)}`,'player');this.db.prepare('INSERT INTO hr_votes VALUES(?,?,?,?,?,?) ON CONFLICT(game_code,round,stage,voter_code) DO UPDATE SET choice=excluded.choice,created_at=excluded.created_at').run(c,g.round,'target',v.player_code,cleanChoice,this.now());return this.voteState(c);}
  retractVote(c,p){const g=this.requireGame(c);this.db.prepare("DELETE FROM hr_votes WHERE game_code=? AND round=? AND stage='target' AND voter_code=?").run(c,g.round,p);return this.voteState(c);}
  voteState(c){const g=this.game(c);if(!g)return[];const votes=this.db.prepare("SELECT stage,voter_code AS voterCode,choice,created_at AS createdAt FROM hr_votes WHERE game_code=? AND round=? AND stage='target'").all(c,g.round),living=this.players(c).filter(p=>p.alive).length;return votes.map(v=>({...v,threshold:Math.floor(living/2)+1}));}
  submitAction(c,p,{targetCode,variant,data,body,asPlayerCode}={}){const g=this.requireGame(c),actor=this.requireAlive(c,p),role=this.role(actor.role_id),action=g.phase==='night'?role.actions.night:role.actions.day;if(!action||action.kind==='sleep')throw new Error('Your role has no active action now');if(effectiveCrippleTier(actor,g.round)>0)throw new Error('Interrogation damage blocks this action');if(action.kind==='forgery')return this.forge(c,p,asPlayerCode,body);const target=this.requireAlive(c,targetCode);if(action.target==='other'&&targetCode===p)throw new Error('Choose another player');if((action.target==='hostile'||action.kind==='kill')&&!isHostileTo(actor,target))throw new Error('Target is not hostile');if(action.variants&&!action.variants.includes(variant))throw new Error('Invalid action variant');if(['sermon','corrupt-sermon'].includes(action.kind)){const s=this.config.drift.sermons[variant],uses=this.usage(c,p,variant);if(s.limit!==null&&uses>=s.limit)throw new Error('Sermon limit reached');
      // TODO(heresy-spec): Whisper is unlimited, Hymn is capped at two, Litany at one, and False Comfort self-cost is +1.
    }this.db.prepare('INSERT INTO hr_actions VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(game_code,round,actor_code) DO UPDATE SET kind=excluded.kind,target_code=excluded.target_code,variant=excluded.variant,data=excluded.data,created_at=excluded.created_at').run(c,g.round,p,action.kind,targetCode,variant,data?JSON.stringify(data):null,this.now());return {kind:action.kind,targetCode,variant};}
  // TODO(heresy-spec): Saboteur trap frequency is once per night; the action table enforces one submission per actor and round.
  // TODO(heresy-spec): Recruiter receives no success/failure detail; failed catalyst attempts are silent.
  actions(c,r){return this.db.prepare('SELECT * FROM hr_actions WHERE game_code=? AND round=?').all(c,r);}
  retractAction(c,p){const g=this.game(c);this.db.prepare('DELETE FROM hr_actions WHERE game_code=? AND round=? AND actor_code=?').run(c,g.round,p);}
  forge(c,p,asPlayerCode,body){const g=this.game(c),actor=this.requireAlive(c,p),as=this.requireAlive(c,asPlayerCode);if(g.phase!=='day')throw new Error('Forgery is day-only');if(this.usage(c,p,`forgery-${g.round}`))throw new Error('Forgery already used today');
    // TODO(heresy-spec): Conspirator default attributes one daily message to another player.
    const message=this.insertMessage(c,'public',null,p,as.name,String(body||'').slice(0,500),'player');this.incrementUsage(c,p,`forgery-${g.round}`);this.changeDrift(c,p,1,'forgery');return {message};}
  usage(c,p,a){return this.db.prepare('SELECT uses FROM hr_usage WHERE game_code=? AND player_code=? AND ability=?').get(c,p,a)?.uses||0;}
  incrementUsage(c,p,a){this.db.prepare('INSERT INTO hr_usage VALUES(?,?,?,1) ON CONFLICT(game_code,player_code,ability) DO UPDATE SET uses=uses+1').run(c,p,a);}
  hints(c){const g=this.game(c);return this.config.hintProfiles[g.hint_profile]||this.config.hintProfiles.default;}
  changeDrift(c,p,delta,reason){const g=this.game(c),player=this.player(c,p);if(!player)return;const before=player.drift,after=Math.max(0,Math.min(g.max_drift,before+delta));this.db.prepare('UPDATE hr_players SET drift=? WHERE game_code=? AND player_code=?').run(after,c,p);const from=driftZone(this.config.drift,before).id,to=driftZone(this.config.drift,after).id;if(from!==to)this.privateSystem(c,p,this.hints(c)[to]);this.event(c,'drift',{playerCode:p,delta,reason,zone:to});}
  finishIfWon(c){const players=this.players(c),living=players.filter(x=>x.alive),h=living.filter(x=>x.faction==='heretic').length,l=living.filter(x=>x.faction==='loyalist').length;let winner=h>=l?'heretic':null;if(!winner&&players.filter(x=>x.faction==='heretic').every(x=>!x.alive||(x.cripple_tier>=3&&x.confessed)))winner='loyalist';if(!winner)return false;
    // TODO(heresy-spec): Pyrrhic/no-clean-win is explicitly deferred from v1.
    this.db.prepare("UPDATE hr_games SET phase='ended',status='ended',winner=?,deadline=NULL WHERE code=?").run(winner,c);this.system(c,`Game over. ${winner} victory.`);return true;}
  sendMessage(c,p,channel,body){const g=this.game(c),player=this.requirePlayer(c,p);this.authorizeChannel(g,player,channel,true);return this.insertMessage(c,channel,null,p,player.name,String(body||'').trim().slice(0,1000),'player');}
  insertMessage(c,ch,recipient,p,author,body,kind){if(!body)throw new Error('Message is empty');const x=this.db.prepare('INSERT INTO hr_messages(game_code,channel,recipient_code,player_code,author,body,kind,created_at) VALUES(?,?,?,?,?,?,?,?)').run(c,ch,recipient,p,author,body,kind,this.now());return this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt FROM hr_messages WHERE id=?').get(x.lastInsertRowid);}
  system(c,b){return this.insertMessage(c,'public',null,null,'The Vox',b,'system');} privateSystem(c,p,b){return this.insertMessage(c,'private',p,null,'The Vox',b,'system');}
  historyMessages(c,p,ch='public',before=Number.MAX_SAFE_INTEGER,limit=50){const g=this.game(c),player=this.requirePlayer(c,p);this.authorizeChannel(g,player,ch,false);return this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? AND channel=? AND id<? ORDER BY id DESC LIMIT ?').all(c,ch,Number(before)||Number.MAX_SAFE_INTEGER,Math.min(100,Number(limit)||50)).reverse();}
  authorizeChannel(g,p,ch,write){if(!['public','faction','graveyard'].includes(ch))throw new Error('Unknown channel');if(ch==='faction'&&p.faction!=='heretic')throw new Error('Faction channel denied');if(ch==='graveyard'&&p.alive)throw new Error('Graveyard denied');if(write&&ch==='public'&&(!p.alive||g.phase==='night'))throw new Error('Public chat is closed');if(write&&ch==='faction'&&g.phase!=='night')throw new Error('Faction chat is night-only');}
  state(c,viewerCode){const g=this.requireGame(c),viewer=this.requirePlayer(c,viewerCode),ended=g.status==='ended',players=this.players(c).map(p=>({playerCode:p.player_code,name:p.name,alive:!!p.alive,ready:!!p.ready,connected:!!p.connected,isHost:p.player_code===g.host_code,crippleTier:p.cripple_tier,confessed:!!p.confessed,...((p.player_code===viewerCode||ended)?{role:p.role_id?this.role(p.role_id):null,faction:p.faction}:{}),...(viewer.faction==='heretic'&&p.faction==='heretic'?{faction:'heretic'}:{})}));const privateMessages=this.db.prepare("SELECT id,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=? ORDER BY id").all(c,viewerCode);// Lobby must not expose role composition; social deduction needs claims to be unknown until private dossier/final reveal.
return {code:c,mode:g.mode,phase:g.phase,dayStage:g.day_stage,status:g.status,round:g.round,deadline:g.deadline,winner:g.winner,maxDrift:g.max_drift,isHost:g.host_code===viewerCode,players,me:players.find(x=>x.playerCode===viewerCode),votes:g.phase==='day'?this.voteState(c):[],myAction:this.db.prepare('SELECT kind,target_code AS targetCode,variant FROM hr_actions WHERE game_code=? AND round=? AND actor_code=?').get(c,g.round,viewerCode)||null,privateMessages,pendingInterrogation:g.day_stage==='response'?{targetCode:g.last_interrogated_target,tier:g.last_interrogation_tier,canRespond:g.last_interrogated_target===viewerCode}:null};}
  adminRole(id){if(!id)return null;const r=this.config.roles.get(id);return r?{id:r.id,displayName:r.displayName,faction:r.faction,claim:r.claim,driftWeight:r.driftWeight,objective:r.objective,ability:r.ability}:null;}
  adminPlayer(p,g){return {playerCode:p.player_code,name:p.name,seat:p.seat,roleId:p.role_id,role:this.adminRole(p.role_id),faction:p.faction,drift:p.drift,alive:!!p.alive,ready:!!p.ready,connected:!!p.connected,isHost:p.player_code===g.host_code,crippleTier:p.cripple_tier,tier1UntilRound:p.tier1_until_round,confessed:!!p.confessed,confessionTokenRound:p.confession_token_round,skipNextNight:!!p.skip_next_night,joinedAt:p.joined_at};}
  adminGameSummary(g){const players=this.players(g.code),messages=this.db.prepare('SELECT COUNT(*) AS count FROM hr_messages WHERE game_code=?').get(g.code).count,events=this.db.prepare('SELECT COUNT(*) AS count FROM hr_events WHERE game_code=?').get(g.code).count,actions=this.db.prepare('SELECT COUNT(*) AS count FROM hr_actions WHERE game_code=?').get(g.code).count,votes=this.db.prepare('SELECT COUNT(*) AS count FROM hr_votes WHERE game_code=?').get(g.code).count;return {code:g.code,mode:g.mode,phase:g.phase,dayStage:g.day_stage,status:g.status,round:g.round,deadline:g.deadline,winner:g.winner,maxDrift:g.max_drift,hintProfile:g.hint_profile,createdAt:g.created_at,updatedAt:g.updated_at,hostCode:g.host_code,playerCount:players.length,aliveCount:players.filter(p=>p.alive).length,connectedCount:players.filter(p=>p.connected).length,readyCount:players.filter(p=>p.ready).length,hereticCount:players.filter(p=>p.faction==='heretic').length,loyalistCount:players.filter(p=>p.faction==='loyalist').length,messageCount:messages,eventCount:events,actionCount:actions,voteCount:votes};}
  adminOverview(){const games=this.db.prepare('SELECT * FROM hr_games ORDER BY updated_at DESC').all().map(g=>this.adminGameSummary(g));return {games,roles:this.roleDefinitions().map(r=>({id:r.id,displayName:r.displayName,faction:r.faction,claim:r.claim,driftWeight:r.driftWeight,objective:r.objective,ability:r.ability})),totals:{games:games.length,active:games.filter(g=>g.status==='active').length,lobby:games.filter(g=>g.status==='lobby').length,ended:games.filter(g=>g.status==='ended').length,players:games.reduce((sum,g)=>sum+g.playerCount,0),messages:games.reduce((sum,g)=>sum+g.messageCount,0)}};}
  adminGame(c){const g=this.requireGame(c),players=this.players(c).map(p=>this.adminPlayer(p,g)),actions=this.db.prepare('SELECT round,actor_code AS actorCode,kind,target_code AS targetCode,variant,data,created_at AS createdAt FROM hr_actions WHERE game_code=? ORDER BY round DESC,created_at DESC').all(c).map(a=>({...a,data:a.data?JSON.parse(a.data):null})),votes=this.db.prepare('SELECT round,stage,voter_code AS voterCode,choice,created_at AS createdAt FROM hr_votes WHERE game_code=? ORDER BY round DESC,created_at DESC').all(c),messages=this.db.prepare('SELECT id,channel,recipient_code AS recipientCode,player_code AS playerCode,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? ORDER BY id DESC LIMIT 200').all(c).reverse(),events=this.db.prepare('SELECT id,type,payload,created_at AS createdAt FROM hr_events WHERE game_code=? ORDER BY id DESC LIMIT 200').all(c).reverse().map(e=>({...e,payload:e.payload?JSON.parse(e.payload):null}));return {game:this.adminGameSummary(g),players,actions,votes,messages,events};}
  adminUpdatePlayer(c,p,updates={}){const existing=this.requirePlayer(c,p),g=this.requireGame(c),fields=[],values=[];const bools={alive:'alive',ready:'ready',connected:'connected',confessed:'confessed',skipNextNight:'skip_next_night'};for(const [input,column] of Object.entries(bools))if(updates[input]!==undefined){fields.push(`${column}=?`);values.push(updates[input]?1:0);}if(updates.drift!==undefined){fields.push('drift=?');values.push(Math.max(0,Math.min(g.max_drift,Number(updates.drift)||0)));}if(updates.crippleTier!==undefined){fields.push('cripple_tier=?');values.push(Math.max(0,Math.min(3,Number(updates.crippleTier)||0)));}if(updates.faction!==undefined&&['loyalist','heretic'].includes(updates.faction)){fields.push('faction=?');values.push(updates.faction);}if(updates.roleId!==undefined){if(updates.roleId&& !this.config.roles.has(updates.roleId))throw new Error('Unknown role');fields.push('role_id=?');values.push(updates.roleId||null);}if(!fields.length)return this.adminPlayer(existing,g);this.db.prepare(`UPDATE hr_players SET ${fields.join(', ')} WHERE game_code=? AND player_code=?`).run(...values,c,p);return this.adminPlayer(this.player(c,p),g);}
  adminEndGame(c,winner='admin'){this.requireGame(c);this.db.prepare("UPDATE hr_games SET phase='ended',status='ended',winner=?,deadline=NULL,updated_at=? WHERE code=?").run(String(winner||'admin').slice(0,30),this.now(),c);this.system(c,`Game ended by admin: ${winner}.`);return this.adminGame(c);}
  adminDeleteGame(c){this.requireGame(c);this.db.transaction(()=>{for(const table of ['hr_actions','hr_votes','hr_messages','hr_usage','hr_events','hr_players'])this.db.prepare(`DELETE FROM ${table} WHERE game_code=?`).run(c);this.db.prepare('DELETE FROM hr_games WHERE code=?').run(c);})();return {deleted:true};}
  due(){return this.db.prepare("SELECT code FROM hr_games WHERE status='active' AND deadline IS NOT NULL AND deadline<=?").all(this.now()).map(x=>x.code);}
  event(c,t,p){this.db.prepare('INSERT INTO hr_events(game_code,type,payload,created_at) VALUES(?,?,?,?)').run(c,t,JSON.stringify(p),this.now());}
  requireGame(c){const g=this.game(c);if(!g)throw new Error('Game not found');return g;}requirePlayer(c,p){const x=this.player(c,p);if(!x)throw new Error('Not a member');return x;}requireAlive(c,p){const x=this.requirePlayer(c,p);if(!x.alive)throw new Error('Dead players cannot do that');return x;}requireHost(c,p){const g=this.requireGame(c);if(g.host_code!==p)throw new Error('Host permission required');return g;}
}
