import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { generateRoomCode, sanitizePlayerName, shuffle } from './utils.js';
import { loadGameConfig } from './gameConfig.js';
import { driftZone, intelNoiseRate, noisyResult } from './mechanics/drift.js';
import { effectiveCrippleTier, getEffectiveScanTier, isExecuteOnSight } from './mechanics/interrogation.js';
import { canProtectSelf, validateRotation, getLastProtectTarget } from './mechanics/protection.js';
import { validateComposition } from './validators/composition.js';
import { saveGameLogSnapshot } from './gameLogs.js';

const schema = `
CREATE TABLE IF NOT EXISTS hr_games(code TEXT PRIMARY KEY,host_code TEXT NOT NULL,mode TEXT NOT NULL,phase TEXT NOT NULL DEFAULT 'lobby',day_stage TEXT,status TEXT NOT NULL DEFAULT 'lobby',round INTEGER NOT NULL DEFAULT 0,deadline INTEGER,day_ms INTEGER NOT NULL,night_ms INTEGER NOT NULL,max_drift INTEGER NOT NULL,hint_profile TEXT NOT NULL DEFAULT 'default',last_interrogated_target TEXT,last_interrogation_tier INTEGER NOT NULL DEFAULT 0,winner TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS hr_players(game_code TEXT NOT NULL,player_code TEXT NOT NULL,name TEXT NOT NULL,seat INTEGER NOT NULL,role_id TEXT,faction TEXT,drift INTEGER NOT NULL DEFAULT 0,alive INTEGER NOT NULL DEFAULT 1,ready INTEGER NOT NULL DEFAULT 0,connected INTEGER NOT NULL DEFAULT 1,cripple_tier INTEGER NOT NULL DEFAULT 0,tier1_until_round INTEGER,confessed INTEGER NOT NULL DEFAULT 0,confession_token_round INTEGER,skip_next_night INTEGER NOT NULL DEFAULT 0,joined_at INTEGER NOT NULL,PRIMARY KEY(game_code,player_code));
CREATE TABLE IF NOT EXISTS hr_actions(game_code TEXT NOT NULL,round INTEGER NOT NULL,actor_code TEXT NOT NULL,kind TEXT NOT NULL,target_code TEXT,variant TEXT,data TEXT,created_at INTEGER NOT NULL,PRIMARY KEY(game_code,round,actor_code));
CREATE TABLE IF NOT EXISTS hr_votes(game_code TEXT NOT NULL,round INTEGER NOT NULL,stage TEXT NOT NULL,voter_code TEXT NOT NULL,choice TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(game_code,round,stage,voter_code));
CREATE TABLE IF NOT EXISTS hr_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,game_code TEXT NOT NULL,channel TEXT NOT NULL,recipient_code TEXT,player_code TEXT,author TEXT NOT NULL,body TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'player',created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS hr_messages_cursor ON hr_messages(game_code,id);
CREATE TABLE IF NOT EXISTS hr_usage(game_code TEXT NOT NULL,player_code TEXT NOT NULL,ability TEXT NOT NULL,uses INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(game_code,player_code,ability));
CREATE TABLE IF NOT EXISTS hr_events(id INTEGER PRIMARY KEY AUTOINCREMENT,game_code TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL);
`;

export function isHostileTo(a, b) {
  // TODO(heresy-spec): v1 hostility is the non-canonical two-faction inequality default.
  return a.faction !== b.faction;
}

export class HeresyGameManager {
  constructor({ databasePath = process.env.GAME_DB_PATH || path.join(process.cwd(), 'data', 'heresy-rising.db'), now = () => Date.now(), random = Math.random } = {}) {
    fs.mkdirSync(path.dirname(databasePath), { recursive: true });
    this.db = new Database(databasePath); this.db.pragma('journal_mode = WAL'); this.db.exec(schema);this.ensureColumn('hr_games','hint_profile',"TEXT NOT NULL DEFAULT 'default'");
    this.ensureColumn('hr_players','is_bot',"INTEGER NOT NULL DEFAULT 0");
    this.ensureColumn('hr_messages','meta',"TEXT");
    this.now = now; this.random = random; this.config = loadGameConfig();
    this._announcementListeners = [];
    this._botPromptListeners = [];
    this._chatMessageListeners = [];
  }
  onAnnouncement(fn){this._announcementListeners.push(fn);}
  emitAnnouncement(c,a){for(const fn of this._announcementListeners)try{fn(c,a);}catch{}}
  onBotPrompt(fn){this._botPromptListeners.push(fn);}
  emitBotPrompt(c,payload){for(const fn of this._botPromptListeners)try{fn(c,payload);}catch{}}
  onChatMessage(fn){this._chatMessageListeners.push(fn);}
  emitChatMessage(c,message){for(const fn of this._chatMessageListeners)try{fn(c,message);}catch{}}
  close(){this.db.close();}
  ensureColumn(table,column,definition){if(!this.db.prepare(`PRAGMA table_info(${table})`).all().some(x=>x.name===column))this.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);}
  game(c){return this.db.prepare('SELECT * FROM hr_games WHERE code=?').get(c);}
  players(c){return this.db.prepare('SELECT * FROM hr_players WHERE game_code=? ORDER BY seat').all(c);}
  player(c,p){return this.db.prepare('SELECT * FROM hr_players WHERE game_code=? AND player_code=?').get(c,p);}
  role(id){const role=this.config.roles.get(id);if(!role)throw new Error('Unknown role data');return role;}
  codes(){return new Set(this.db.prepare('SELECT code FROM hr_games').all().map(x=>x.code));}
  presetFor(count){
    // TODO(heresy-spec): Entire 5–12 composition table and priority fallback are non-canonical, unplaytested defaults.
    const exact=this.config.composition[String(count)]; if(exact)return [...exact];
    const roles=this.config.composition.fallbackPriority.slice(0,Math.max(0,count-1));
    while(roles.length<count)roles.push('imperial-citizen'); return roles.slice(0,count);
  }
  roleDefinitions(){return this.config.roleList.map(({ability,objective,...role})=>({...role,ability,objective}));}
  create({playerCode,name,mode='live',options={}}){
    if(!playerCode)throw new Error('playerCode is required'); if(!['live','async'].includes(mode))throw new Error('Invalid game mode');
    const code=generateRoomCode(this.codes(),6),now=this.now(),dayMs=Number(options.dayMs)||(mode==='async'?86400000:300000),nightMs=Number(options.nightMs)||(mode==='async'?43200000:120000),max=Math.max(1,Number(options.maxDrift)||this.config.drift.MAX_DRIFT),hintProfile=this.config.hintProfiles[options.hintProfile] ? options.hintProfile : 'default';
    this.db.prepare('INSERT INTO hr_games(code,host_code,mode,day_ms,night_ms,max_drift,hint_profile,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(code,playerCode,mode,dayMs,nightMs,max,hintProfile,now,now);
    this.db.prepare('INSERT INTO hr_players(game_code,player_code,name,seat,joined_at) VALUES(?,?,?,?,?)').run(code,playerCode,sanitizePlayerName(name),0,now); return {code,state:this.state(code,playerCode)};
  }
  join({code,playerCode,name}){const g=this.requireGame(code);let p=this.player(code,playerCode);if(!p){if(g.phase!=='lobby')throw new Error('Game already started');const count=this.players(code).length;if(count>=12)throw new Error('Game is full');this.db.prepare('INSERT INTO hr_players(game_code,player_code,name,seat,joined_at) VALUES(?,?,?,?,?)').run(code,playerCode,sanitizePlayerName(name),count,this.now());}else this.db.prepare('UPDATE hr_players SET connected=1 WHERE game_code=? AND player_code=?').run(code,playerCode);return this.state(code,playerCode);}
  disconnect(playerCode,gameCode){if(gameCode)this.db.prepare('UPDATE hr_players SET connected=0 WHERE game_code=? AND player_code=?').run(gameCode,playerCode);else this.db.prepare('UPDATE hr_players SET connected=0 WHERE player_code=?').run(playerCode);}
reconnect(c,p){this.requirePlayer(c,p);this.db.prepare('UPDATE hr_players SET connected=1 WHERE game_code=? AND player_code=?').run(c,p);return this.state(c,p);}
  kick(c,hostCode,targetCode){const g=this.requireHost(c,hostCode);const target=this.requirePlayer(c,targetCode);if(target.player_code===hostCode)throw new Error('Host cannot kick themselves');if(g.phase!=='lobby')throw new Error('Kick is only allowed in the lobby');this.db.prepare('DELETE FROM hr_players WHERE game_code=? AND player_code=?').run(c,targetCode);return this.state(c,hostCode);}
  ready(c,p,value){this.requirePlayer(c,p);this.db.prepare('UPDATE hr_players SET ready=? WHERE game_code=? AND player_code=?').run(value===undefined?1:+!!value,c,p);return this.state(c,p);}
  start(c,p,{maxDrift,dayMs,nightMs,composition}={}){
    const g=this.requireHost(c,p),players=this.players(c);
    if(g.phase!=='lobby')throw new Error('Already started');
    if(players.length<5||players.length>12)throw new Error('Games require 5–12 players');
    if(players.some(x=>x.player_code!==p&&!x.ready))throw new Error('All players must be ready');

    let ids, compositionSource;
    if(!composition){
      ids=this.presetFor(players.length);
      compositionSource='preset';
    }else if(composition.source==='preset'){
      const presetCount=parseInt(String(composition.presetId).replace('p',''))||players.length;
      ids=this.presetFor(presetCount);
      compositionSource='preset';
    }else if(composition.source==='custom'){
      ids=[...composition.roster];
      compositionSource='custom';
    }else{
      throw new Error('Invalid composition source');
    }

    const validation=validateComposition({
      roster:ids,
      playerCount:players.length,
      confirmedWarnings:composition?.confirmedWarnings||[],
      validRoles:this.config.roles,
      hardRules:this.config.hardRules,
      source:compositionSource
    });
    if(!validation.ok)return{ok:false,phase:'lobby',composition:{submitted:ids,source:compositionSource},errors:validation.errors,warnings:validation.warnings};

    const assigned=shuffle(ids);
    const fallbackDay=g.mode==='async'?86_400_000:300_000,fallbackNight=g.mode==='async'?43_200_000:120_000;
    const resolvedDayMs=Math.max(10_000,Number(dayMs)||fallbackDay),resolvedNightMs=Math.max(10_000,Number(nightMs)||fallbackNight);
    const startDeadline=this.now()+resolvedDayMs;
    this.db.transaction(()=>{
      players.forEach((x,i)=>{const r=this.role(assigned[i]);this.db.prepare('UPDATE hr_players SET role_id=?,faction=?,drift=0,alive=1,cripple_tier=0,confessed=0 WHERE game_code=? AND player_code=?').run(r.id,r.faction,c,x.player_code);});
      this.db.prepare("UPDATE hr_games SET phase='day',day_stage='vote',status='active',round=1,max_drift=?,day_ms=?,night_ms=?,deadline=?,updated_at=? WHERE code=?").run(Math.max(1,Number(maxDrift)||g.max_drift),resolvedDayMs,resolvedNightMs,startDeadline,this.now(),c);
      // Wipe lobby chatter so the live game starts with a clean transcript.
      this.db.prepare("DELETE FROM hr_messages WHERE game_code=?").run(c);
      this.system(c,'Roles sealed. Day 1 begins — review your dossier and discuss.');
    })();
    players.forEach((x,i)=>{const r=this.role(assigned[i]);this.privateSystem(c,x.player_code,`Your role is ${r.displayName}. ${r.objective}`);this.emitAnnouncement(c,{type:'role-reveal',title:'YOUR DOSSIER',message:`You are a ${r.displayName}. ${r.objective}`,role:r.displayName,objective:r.objective,faction:r.faction,round:1,phase:'day',targetCode:x.player_code});});
    return this.state(c,p);
  }
  configure(c,p,options={}){const g=this.requireGame(c);if(g.phase!=='lobby')throw new Error('Game has already started');this.requireHost(c,p);const dayMs=Math.max(60000,Math.min(86400000,Number(options.dayMs)||g.day_ms)),nightMs=Math.max(60000,Math.min(86400000,Number(options.nightMs)||g.night_ms)),maxDrift=Math.max(1,Math.min(100,Number(options.maxDrift)||g.max_drift));this.db.prepare('UPDATE hr_games SET day_ms=?,night_ms=?,max_drift=?,updated_at=? WHERE code=?').run(dayMs,nightMs,maxDrift,this.now(),c);return this.state(c,p);}
  advance(c,p){this.requireHost(c,p);return this.resolve(c,true);}
  resolve(c,force=false){const g=this.requireGame(c);if(g.status!=='active')throw new Error('Game is not active');if(!force&&g.deadline&&g.deadline>this.now())throw new Error('Phase is active');if(g.phase==='night')this.resolveNight(g);else if(g.phase==='day')this.resolveDay(g);return this.game(c);}
  // TODO(heresy-spec): Q28 — Day 1 votingEnabled = false. Remove when gate is wired.
  setPhase(c,phase,round,dayStage=null){const g=this.game(c),duration=phase==='night'?g.night_ms:g.day_ms,deadline=this.now()+duration,stage=phase==='day'?(dayStage||'vote'):dayStage;this.db.prepare('UPDATE hr_games SET phase=?,round=?,day_stage=?,deadline=?,updated_at=? WHERE code=?').run(phase,round,stage,deadline,this.now(),c);if(phase==='night')this.db.prepare('UPDATE hr_players SET confession_token_round=NULL WHERE game_code=?').run(c);if(phase==='day'){this.db.prepare('UPDATE hr_players SET cripple_tier=0,tier1_until_round=NULL WHERE game_code=? AND cripple_tier=1 AND tier1_until_round<?').run(c,round);const votingEnabled=round!==1;this.system(c,votingEnabled?`Day ${round}: vote for a target or stand down.`:`Day ${round} begins — no vote today. Introduce yourself and observe.`);}
  // Bot prompts: nudge bot sockets to act. Night → night_action_prompt; voting-enabled day → day_vote_prompt. Day 1 has no vote (Q28) → no prompt.
  const aliveBots=this.players(c).filter(p=>p.alive&&p.is_bot);
  if(phase==='night')for(const p of aliveBots)this.emitBotPrompt(c,{kind:'night_action_prompt',playerCode:p.player_code,round,deadline});
  else if(phase==='day'&&round!==1)for(const p of aliveBots){const targets=this.players(c).filter(x=>x.alive&&x.player_code!==p.player_code).map(x=>x.player_code);this.emitBotPrompt(c,{kind:'day_vote_prompt',playerCode:p.player_code,round,votingEnabled:true,deadline,legalTargets:targets});}}
  resolveNight(g){const c=g.code,players=this.players(c).filter(p=>p.alive),actions=this.actions(c,g.round),traps=new Map(actions.filter(a=>a.kind==='boobytrap').map(a=>[a.target_code,a]));const protectedIds=new Set(),bodyguards=new Map();
    for(const p of players){const a=actions.find(x=>x.actor_code===p.player_code),role=this.role(p.role_id);if(p.skip_next_night){this.db.prepare('UPDATE hr_players SET skip_next_night=0 WHERE game_code=? AND player_code=?').run(c,p.player_code);continue;}if(!a){this.changeDrift(c,p.player_code,this.config.drift.NIGHTLY_SLEEP_RECOVERY,'sleep');continue;}this.changeDrift(c,p.player_code,role.driftWeight,'night-action');}
    for(const a of actions.filter(x=>x.kind==='protect'))if(!this.trapBlocks(c,g,a,traps))protectedIds.add(a.target_code);
    for(const a of actions.filter(x=>x.kind==='bodyguard'))if(!this.trapBlocks(c,g,a,traps))bodyguards.set(a.target_code,a.actor_code);
    for(const a of actions.filter(x=>['sermon','corrupt-sermon'].includes(x.kind))){if(this.trapBlocks(c,g,a,traps))continue;const s=this.config.drift.sermons[a.variant];this.changeDrift(c,a.actor_code,s.self,'sermon-self');this.changeDrift(c,a.target_code,s.target,'sermon-target');this.incrementUsage(c,a.actor_code,a.variant);}
    const autoKills=[];for(const a of actions.filter(x=>['investigate','drift-hint'].includes(x.kind))){if(this.trapBlocks(c,g,a,traps))continue;const result=this.resolveIntel(c,a);if(result?.autoKill)autoKills.push(result);}for(const k of autoKills){const victim=this.player(c,k.targetCode);if(!victim?.alive)continue;this.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(c,k.targetCode);this.system(c,`${victim.name} was executed by Interrogator. Confirmed warp-touched.`);this.system(c,`${victim.name}'s alignment: ${victim.faction}.`);if(k.actorCode)this.privateSystem(c,k.actorCode,`Your scan executed ${victim.name}. Warp-touched confirmed.`,{intelKind:'execute_on_sight',action:'interrogate',target:k.targetCode,zone:k.zone,faction:k.faction});this.emitAnnouncement(c,{type:'execution',title:'SUMMARY EXECUTION',message:`${victim.name} was executed by order of the Interrogator.`,victim:{name:victim.name,faction:victim.faction},round:g.round,phase:'night'});for(const w of players)this.changeDrift(c,w.player_code,this.config.drift.WITNESSED_VIOLENCE,'witnessed-violence');}
    for(const a of actions.filter(x=>x.kind==='heretical-catalyst')){const target=this.player(c,a.target_code);if(traps.has(a.target_code))this.changeDrift(c,a.actor_code,this.config.drift.TRAP_DRIFT,'trap');if(target?.drift>=g.max_drift&&!protectedIds.has(a.target_code)){this.db.prepare("UPDATE hr_players SET faction='heretic' WHERE game_code=? AND player_code=?").run(c,a.target_code);this.privateSystem(c,a.target_code,'The catalyst takes hold. Your loyalty has burned away.');}}
    for(const kill of actions.filter(x=>x.kind==='kill')){const killer=this.player(c,kill.actor_code);if(!killer?.alive)continue;if(traps.has(kill.actor_code)){this.changeDrift(c,kill.actor_code,this.config.drift.TRAP_DRIFT,'trap');continue;}if(traps.has(kill.target_code))this.changeDrift(c,kill.actor_code,this.config.drift.TRAP_DRIFT,'trap');let victim=kill.target_code,bodyguardRedirected=false;if(bodyguards.has(victim)){const guardCode=bodyguards.get(victim);this.privateSystem(c,guardCode,'You absorbed a strike meant for your proxy and died.');victim=guardCode;bodyguardRedirected=true;}if(!bodyguardRedirected&&protectedIds.has(kill.target_code))victim=null;if(victim){this.db.prepare('UPDATE hr_players SET alive=0 WHERE game_code=? AND player_code=?').run(c,victim);const victimName=this.player(c,victim).name,killerName=killer.name;if(bodyguards.has(kill.target_code)){const targetName=this.player(c,kill.target_code).name;const redirectBody=this.flavor('bodyguardRedirect',{victim:victimName,target:targetName});this.system(c,redirectBody);this.emitAnnouncement(c,{type:'bodyguard',title:'BLADE DEFLECTED',message:redirectBody,victim:{name:victimName},perpetrator:{name:killerName},round:g.round,phase:'night'});}else{const slainBody=this.flavor('slain',{victim:victimName});this.system(c,slainBody);this.emitAnnouncement(c,{type:'kill',title:'SLAIN IN THE NIGHT',message:slainBody,victim:{name:victimName},perpetrator:{name:killerName},round:g.round,phase:'night'});}for(const witness of this.players(c).filter(x=>x.alive))this.changeDrift(c,witness.player_code,this.config.drift.WITNESSED_VIOLENCE,'witnessed-violence');}const killRole=this.role(killer.role_id);if(killRole.killLimit==='1_per_game')this.incrementUsage(c,kill.actor_code,'kill');}
    if(!this.finishIfWon(c)){this.setPhase(c,'day',g.round+1,'vote');}}
  trapBlocks(c,g,a,traps){if(!traps.has(a.target_code))return false;this.changeDrift(c,a.actor_code,this.config.drift.TRAP_DRIFT,'trap');const trap=traps.get(a.target_code);this.privateSystem(c,trap.actor_code,`Your trap caught ${this.player(c,a.actor_code).name} targeting ${this.player(c,a.target_code).name}.`);return !['kill','heretical-catalyst'].includes(a.kind);}
  resolveIntel(c,a){const actor=this.player(c,a.actor_code),target=this.player(c,a.target_code),role=this.role(actor.role_id);if(a.kind==='drift-hint'){const targetZone=driftZone(this.config.drift,target.drift);const rate=intelNoiseRate(this.config.drift,target.drift,role.driftWeight);const truth=targetZone.id;const zones=this.config.drift.zones;const truthIdx=zones.findIndex(z=>z.id===truth);let shown=truth;if(this.random()<rate){const left=truthIdx>0?truthIdx-1:truthIdx+1;const right=truthIdx<zones.length-1?truthIdx+1:truthIdx-1;const adj=this.random()<0.5?left:right;shown=zones[adj].id;}this.privateSystem(c,a.actor_code,this.hints(c)[shown],{intelKind:'drift-hint',action:'scan_drift',target:a.target_code,zone:shown});return{};}const intensity=Number(String(a.variant||'T1').replace('T',''))||1;const targetZone=driftZone(this.config.drift,target.drift);if(isExecuteOnSight(intensity,targetZone.id))return{autoKill:true,actorCode:a.actor_code,targetCode:a.target_code,zone:targetZone.id,faction:target.faction};if(intensity===1){const groundTruth=targetZone.id==='green'?'Clean':'Tainted';const isTrue=this.random()<0.7;const display=isTrue?groundTruth:(groundTruth==='Clean'?'Tainted':'Clean');this.privateSystem(c,a.actor_code,`Target: ${display}.`,{intelKind:'interrogate',tier:1,target:a.target_code,zone:targetZone.id,result:display.toLowerCase()});return{};}const effectiveTier=getEffectiveScanTier(intensity,targetZone.id);const rate=intelNoiseRate(this.config.drift,actor.drift,role.driftWeight);if(effectiveTier>=3){const text=target.faction==='loyalist'?'Confirmed: they are a Loyalist. The Emperor\'s light is unbroken in them.':'Confirmed: they are a Heretic. The warp taint is undeniable.';this.privateSystem(c,a.actor_code,text,{intelKind:'interrogate',tier:intensity,effectiveTier,target:a.target_code,zone:targetZone.id,faction:target.faction});return{};}const truth=target.faction==='loyalist';const result=noisyResult(truth,rate,this.random);let text=result==='unclear'?'You learned nothing.':result?'Their story holds together.':'Something does not add up.';if(effectiveTier>=2)text+=` You sense their drift zone: ${targetZone.id}.`;this.privateSystem(c,a.actor_code,text,{intelKind:'interrogate',tier:intensity,effectiveTier,target:a.target_code,zone:effectiveTier>=2?targetZone.id:null,factionHint:result==='unclear'?null:(result?'loyalist':'heretic')});return{};}
    // TODO(heresy-spec): Q28 — Day 1 votingEnabled = false. Remove when gate is wired.
  resolveDay(g){if(g.day_stage==='response')throw new Error('Awaiting interrogation response or direct ask');const votingEnabled=g.round!==1;if(!votingEnabled){const payload={round:g.round,outcome:'skip',target:null,reason:'day1-no-vote',voterResults:[],witnessedDrift:0,alignmentRevealed:null,crippleTier:null};this.event(g.code,'day-resolution',payload);this.system(g.code,`Day ${g.round} concludes with no vote. The conclave disperses.`);this.applyHereticCap(g.code,g.round);if(!this.finishIfWon(g.code))this.setPhase(g.code,'night',g.round);return payload;}return this.resolveDayVote(g);}
  dayVotes(c,r){return this.db.prepare("SELECT * FROM hr_votes WHERE game_code=? AND round=? AND stage='target'").all(c,r);}
  resolveDayVote(g){
    const c=g.code,living=this.players(c).filter(p=>p.alive),votes=this.dayVotes(c,g.round),skipCount=votes.filter(v=>v.choice==='skip').length,totalAlive=living.length,threshold=Math.floor(totalAlive/2)+1;
    if(skipCount>totalAlive/2){this.system(c,`Vote tally — Stand down carried: ${skipCount} of ${totalAlive} voted to stand down (${threshold} needed to convict). The conclave dispersed.`);return this.skipDay(g,'skip-majority');}
    const counts=new Map();for(const v of votes){if(v.choice==='skip')continue;const target=this.player(c,v.choice);if(target?.alive)counts.set(v.choice,(counts.get(v.choice)||0)+1);}
    if(counts.size===0){this.system(c,'Vote tally — No votes were cast for any candidate. The conclave dispersed.');return this.skipDay(g,'no-votes');}
    const top=Math.max(...counts.values());
    if(top<threshold){const leaders=[...counts].filter(([,count])=>count===top).map(([code])=>this.player(c,code)?.name).filter(Boolean);this.system(c,`Vote tally — No candidate reached the threshold: ${leaders.join(', ')} led with ${top} (${threshold} needed of ${totalAlive} alive). The conclave dispersed.`);return this.skipDay(g,'threshold-not-met');}
    let leaderCodes=[...counts].filter(([,count])=>count===top).map(([code])=>code);
    if(leaderCodes.length>1){const maxDrift=Math.max(...leaderCodes.map(code=>this.player(c,code)?.drift??-1));leaderCodes=leaderCodes.filter(code=>(this.player(c,code)?.drift??-1)===maxDrift);if(leaderCodes.length!==1){const leaderNames=leaderCodes.map(code=>this.player(c,code)?.name).filter(Boolean);this.system(c,`Vote tally — Tied between ${leaderNames.join(', ')} at ${top} votes (${threshold} needed of ${totalAlive} alive); drift could not break it. The conclave dispersed.`);return this.skipDay(g,'tied-drift');}}
    const targetCode=leaderCodes[0],targetName=this.player(c,targetCode)?.name||'someone',targetVotes=votes.filter(v=>v.choice===targetCode),voterNames=targetVotes.map(v=>this.player(c,v.voter_code)?.name||'?').filter(Boolean),previous=this.previousDayResolution(c,g.round),samePrevious=previous?.outcome==='interrogate'&&previous.target===targetCode&&this.player(c,targetCode)?.alive,outcome=samePrevious?'lynch':'interrogate';
    this.system(c,`Vote tally — ${targetName} reached ${targetVotes.length} of ${totalAlive} votes (${threshold} needed). Voters: ${voterNames.join(', ')}.`);
    return outcome==='lynch'?this.applyLynch(g,targetCode):this.applyInterrogation(g,targetCode);
  }
  previousDayResolution(c,round){const row=this.db.prepare("SELECT payload FROM hr_events WHERE game_code=? AND type='day-resolution' ORDER BY id DESC LIMIT 1").get(c);if(!row)return null;try{const payload=JSON.parse(row.payload);return payload.round===round-1?payload:null;}catch{return null;}}
  skipDay(g,reason='skip'){const c=g.code,payload={round:g.round,outcome:'skip',target:null,reason,voterResults:this.dayVotes(c,g.round).map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0})),witnessedDrift:0,alignmentRevealed:null,crippleTier:null};this.event(c,'day-resolution',payload);this.system(c,'The conclave stands down. No sentence is passed.');this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round);return payload;}
  applyInterrogation(g,targetCode){const c=g.code,target=this.player(c,targetCode);if(!target?.alive){this.system(c,'Vote tally — The leading candidate was already dead; the conclave dispersed without judgement.');return this.skipDay(g,'invalid-target');}if(target.cripple_tier>=3){this.system(c,`Vote tally — ${target.name} was already at Tier 3 and cannot be interrogated again; the conclave dispersed without judgement.`);return this.skipDay(g,'target-already-crippled');}const tier=Math.min(3,(Number(target.cripple_tier)||0)+1),voters=this.dayVotes(c,g.round).filter(v=>v.choice===targetCode);this.db.prepare('UPDATE hr_games SET last_interrogated_target=?,last_interrogation_tier=?,day_stage=?,deadline=NULL,updated_at=? WHERE code=?').run(targetCode,tier,null,this.now(),c);this.db.prepare('UPDATE hr_players SET cripple_tier=?,tier1_until_round=? WHERE game_code=? AND player_code=?').run(tier,tier===1?g.round:null,c,targetCode);const voterResults=voters.map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0}));let witnessedDrift=0;if(target.faction==='loyalist'){for(const result of voterResults){result.driftDelta=1;this.changeDrift(c,result.voter,1,'wrong-interrogation');}}else if(target.faction==='heretic'){witnessedDrift=-1;for(const p of this.players(c).filter(x=>x.alive))this.changeDrift(c,p.player_code,-1,'right-interrogation-cleansing');}const payload={round:g.round,outcome:'interrogate',target:targetCode,voterResults,witnessedDrift,alignmentRevealed:null,crippleTier:tier};this.event(c,'day-resolution',payload);const tortureBody=this.flavor('tortureChamber',{victim:target.name,tier});this.system(c,tortureBody);this.emitAnnouncement(c,{type:'torture-chamber',title:'TORTURE CHAMBER',message:tortureBody,victim:{name:target.name},round:g.round,phase:'day'});this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round);return payload;}
  applyLynch(g,targetCode){const c=g.code,target=this.player(c,targetCode),votes=this.dayVotes(c,g.round).filter(v=>v.choice===targetCode),voterResults=votes.map(v=>({voter:v.voter_code,votedFor:v.choice,driftDelta:0}));this.db.prepare('UPDATE hr_players SET cripple_tier=3,alive=0 WHERE game_code=? AND player_code=?').run(c,targetCode);this.system(c,`${target.name} was lynched and revealed ${target.faction}.`);this.emitAnnouncement(c,{type:'lynch',title:'SENTENCE EXECUTED',message:`${target.name} was lynched and revealed as ${target.faction}.`,victim:{name:target.name,faction:target.faction},round:g.round,phase:'day'});for(const p of this.players(c).filter(x=>x.alive))this.changeDrift(c,p.player_code,1,'witnessed-violence');if(target.faction==='loyalist')for(const result of voterResults){result.driftDelta=this.config.drift.WRONG_LYNCH;this.changeDrift(c,result.voter,this.config.drift.WRONG_LYNCH,'wrong-lynch');}const payload={round:g.round,outcome:'lynch',target:targetCode,voterResults,witnessedDrift:1,alignmentRevealed:target.faction,crippleTier:3};this.event(c,'day-resolution',payload);this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round);return payload;}
  respondInterrogation(c,p,response){const g=this.requireGame(c),target=this.player(c,p);if(g.phase!=='day'||g.day_stage!=='response'||g.last_interrogated_target!==p)throw new Error('No response is pending');if(target.cripple_tier>=3)throw new Error('Tier 3 requires a direct ask');if(!['confess','resist','refuse-break'].includes(response))throw new Error('Invalid response');if(response==='confess'){
      // TODO(heresy-spec): Confession token blocks same-day re-interrogation, expires Day→Night, does not stack, and skips the next night action.
      this.db.prepare('UPDATE hr_players SET confessed=1,confession_token_round=?,skip_next_night=1 WHERE game_code=? AND player_code=?').run(g.round,c,p);this.system(c,`${target.name} confessed: ${this.role(target.role_id).displayName}.`);this.emitAnnouncement(c,{type:'confession',title:'CONFESSION',message:`${target.name} confessed: ${this.role(target.role_id).displayName}.`,victim:{name:target.name},round:g.round,phase:'day'});}else if(response==='resist')this.changeDrift(c,p,1,'resist');else{this.db.prepare('UPDATE hr_players SET cripple_tier=MAX(cripple_tier,2),skip_next_night=1 WHERE game_code=? AND player_code=?').run(c,p);this.changeDrift(c,p,2,'refuse-break');}this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round);return this.state(c,p);}
  askConfession(c,asker,targetCode){const g=this.requireGame(c);this.requireAlive(c,asker);const target=this.requirePlayer(c,targetCode);if(g.phase!=='day'||g.day_stage!=='response'||targetCode!==g.last_interrogated_target||target.cripple_tier<3)throw new Error('This player cannot be asked now');
    // TODO(heresy-spec): Tier 3 confession occurs only on a direct ask and is required for Loyalist victory.
    this.db.prepare('UPDATE hr_players SET confessed=1 WHERE game_code=? AND player_code=?').run(c,targetCode);this.system(c,`${target.name} is forced to confess: ${this.role(target.role_id).displayName}.`);this.emitAnnouncement(c,{type:'confession',title:'FORCED CONFESSION',message:`${target.name} is forced to confess: ${this.role(target.role_id).displayName}.`,victim:{name:target.name},round:g.round,phase:'day'});this.applyHereticCap(c,g.round);if(!this.finishIfWon(c))this.setPhase(c,'night',g.round);return this.state(c,asker);}
  applyHereticCap(c,day){if(day!==this.config.drift.HERETIC_CAP_DAY)return;for(const p of this.players(c).filter(x=>x.alive&&x.faction==='heretic'&&x.drift<this.config.drift.HERETIC_DRIFT_CAP))this.changeDrift(c,p.player_code,this.config.drift.HERETIC_CAP_SPIKE,'heretic-cap');}
  // TODO(heresy-spec): Q28 — Day 1 votingEnabled = false. Remove when gate is wired.
  vote(c,p,choice,justification=''){const g=this.requireGame(c),v=this.requireAlive(c,p),cleanChoice=String(choice||'');if(g.phase!=='day'||g.day_stage==='response'||g.round===1)throw new Error('Voting is closed');if(cleanChoice!=='skip')this.requireAlive(c,cleanChoice);if(effectiveCrippleTier(v,g.round)>=2&&!String(justification).trim())throw new Error('Broken players must justify every vote');const targetName=cleanChoice==='skip'?null:this.player(c,cleanChoice)?.name||'Unknown';const voteMsg=targetName?`${v.name} accused ${targetName}.`:`${v.name} stood down.`;this.system(c,voteMsg);const message=justification?this.insertMessage(c,'public',null,p,v.name,`Vote justification: ${String(justification).trim().slice(0,300)}`,'vote'):null;this.db.prepare('INSERT INTO hr_votes VALUES(?,?,?,?,?,?) ON CONFLICT(game_code,round,stage,voter_code) DO UPDATE SET choice=excluded.choice,created_at=excluded.created_at').run(c,g.round,'target',v.player_code,cleanChoice,this.now());return{votes:this.voteState(c),message};}
  retractVote(c,p){const g=this.requireGame(c),v=this.player(c,p);this.db.prepare("DELETE FROM hr_votes WHERE game_code=? AND round=? AND stage='target' AND voter_code=?").run(c,g.round,p);if(v?.alive)this.system(c,`${v.name} retracted their accusation.`);return this.voteState(c);}
  voteState(c){const g=this.game(c);if(!g)return[];const votes=this.db.prepare("SELECT stage,voter_code AS voterCode,choice,created_at AS createdAt FROM hr_votes WHERE game_code=? AND round=? AND stage='target'").all(c,g.round),living=this.players(c).filter(p=>p.alive).length;return votes.map(v=>({...v,threshold:Math.floor(living/2)+1}));}
  submitAction(c,p,{targetCode,variant,data,body,asPlayerCode}={}){const g=this.requireGame(c),actor=this.requireAlive(c,p),role=this.role(actor.role_id),action=g.phase==='night'?role.actions.night:role.actions.day;if(!action||action.kind==='sleep')throw new Error('Your role has no active action now');if(action.kind==='protect'&&effectiveCrippleTier(actor,g.round)>0)return{kind:'protect',targetCode,silent:true};if(action.kind==='bodyguard'&&effectiveCrippleTier(actor,g.round)>0)return{kind:'bodyguard',targetCode,silent:true};if(action.kind==='drift-hint'&&effectiveCrippleTier(actor,g.round)>0)return{kind:'drift-hint',targetCode,silent:true};if(effectiveCrippleTier(actor,g.round)>0)throw new Error('Interrogation damage blocks this action');if(action.kind==='kill'&&role.killLimit){const killUses=this.usage(c,p,'kill');if(killUses>=1)throw new Error('You can only use your kill once per game');}
if(action.kind==='forgery')return this.forge(c,p,asPlayerCode,body);const target=this.requireAlive(c,targetCode);if(action.target==='other'&&!canProtectSelf(role.id)&&targetCode===p)throw new Error('Choose another player');if(action.kind==='protect'&&!validateRotation(this.db,c,p,targetCode,g.round))throw new Error('Cannot protect the same target on consecutive nights');if(action.kind==='bodyguard'&&!validateRotation(this.db,c,p,targetCode,g.round))throw new Error('Cannot proxy the same target on consecutive nights');if((action.target==='hostile'||action.kind==='kill')&&!isHostileTo(actor,target))throw new Error('Target is not hostile');if(action.variants&&!action.variants.includes(variant))throw new Error('Invalid action variant');if(['sermon','corrupt-sermon'].includes(action.kind)){const s=this.config.drift.sermons[variant],uses=this.usage(c,p,variant);if(s.limit!==null&&uses>=s.limit)throw new Error('Sermon limit reached');
      if(action.kind==='corrupt-sermon'&&variant==='warp-litany'&&target.drift<(s.target_zone_min_drift??10))return{ok:false,silent:true};
    }this.db.prepare('INSERT INTO hr_actions VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(game_code,round,actor_code) DO UPDATE SET kind=excluded.kind,target_code=excluded.target_code,variant=excluded.variant,data=excluded.data,created_at=excluded.created_at').run(c,g.round,p,action.kind,targetCode,variant,data?JSON.stringify(data):null,this.now());if(g.phase==='night'&&actor.faction==='heretic'){const cabalLabel=action.kind==='kill'?`marked ${target.name} for death`:action.kind==='boobytrap'?`set a trap on ${target.name}`:action.kind==='corrupt-sermon'?`targets ${target.name} with a corrupt sermon`:action.kind==='heretical-catalyst'?`invokes the catalyst on ${target.name}`:`uses ${action.kind}`;this.factionSystem(c,`Cabalite ${actor.name} ${cabalLabel}.`);}return {kind:action.kind,targetCode,variant};}
  // TODO(heresy-spec): Saboteur trap frequency is once per night; the action table enforces one submission per actor and round.
  // TODO(heresy-spec): Recruiter receives no success/failure detail; failed catalyst attempts are silent.
  actions(c,r){return this.db.prepare('SELECT * FROM hr_actions WHERE game_code=? AND round=?').all(c,r);}
  retractAction(c,p){const g=this.game(c);this.db.prepare('DELETE FROM hr_actions WHERE game_code=? AND round=? AND actor_code=?').run(c,g.round,p);}
  forge(c,p,asPlayerCode,body){const g=this.game(c),actor=this.requireAlive(c,p),as=this.requireAlive(c,asPlayerCode);if(g.phase!=='day')throw new Error('Forgery is day-only');if(this.usage(c,p,`forgery-${g.round}`))throw new Error('Forgery already used today');
    // TODO(heresy-spec): Conspirator default attributes one daily message to another player.
    const message=this.insertMessage(c,'public',null,p,as.name,String(body||'').slice(0,500),'player');this.incrementUsage(c,p,`forgery-${g.round}`);this.changeDrift(c,p,1,'forgery');return {message};}
  usage(c,p,a){return this.db.prepare('SELECT uses FROM hr_usage WHERE game_code=? AND player_code=? AND ability=?').get(c,p,a)?.uses||0;}
  incrementUsage(c,p,a){this.db.prepare('INSERT INTO hr_usage VALUES(?,?,?,1) ON CONFLICT(game_code,player_code,ability) DO UPDATE SET uses=uses+1').run(c,p,a);}
  hints(c){const g=this.game(c);return this.config.hintProfiles[g.hint_profile]||this.config.hintProfiles.default;}
  changeDrift(c,p,delta,reason){const g=this.game(c),player=this.player(c,p);if(!player)return;const before=player.drift,after=Math.max(0,Math.min(g.max_drift,before+delta));this.db.prepare('UPDATE hr_players SET drift=? WHERE game_code=? AND player_code=?').run(after,c,p);const from=driftZone(this.config.drift,before).id,to=driftZone(this.config.drift,after).id;if(from!==to)this.privateSystem(c,p,this.hints(c)[to],{intelKind:'drift_hint',ownZone:to});this.event(c,'drift',{playerCode:p,delta,before,after,reason,zone:to,round:g.round,phase:g.phase});}
  finishIfWon(c){const players=this.players(c),living=players.filter(x=>x.alive),h=living.filter(x=>x.faction==='heretic').length,l=living.filter(x=>x.faction==='loyalist').length;let winner=h>=l?'heretic':null;if(!winner&&players.filter(x=>x.faction==='heretic').every(x=>!x.alive||(x.cripple_tier>=3&&x.confessed)))winner='loyalist';if(!winner)return false;
    // TODO(heresy-spec): Pyrrhic/no-clean-win is explicitly deferred from v1.
    this.db.prepare("UPDATE hr_games SET phase='ended',status='ended',winner=?,deadline=NULL WHERE code=?").run(winner,c);this.system(c,`Game over. ${winner} victory.`);const gEnd=this.game(c);this.emitAnnouncement(c,{type:'gameover',title:'GAME OVER',message:`${winner} victory. The conclave is dissolved.`,winner,round:gEnd.round});saveGameLogSnapshot({gameLogId:c,code:c,phase:gEnd.phase,winner:gEnd.winner,round:gEnd.round,maxDrift:gEnd.max_drift,mode:gEnd.mode,status:gEnd.status,players:this.players(c).map(p=>({id:p.player_code,name:p.name,hero:p.role_id||null,playerCode:p.player_code,seat:p.seat,roleId:p.role_id||null,faction:p.faction,drift:p.drift,alive:!!p.alive,crippleTier:p.cripple_tier,isBot:!!p.is_bot})),debugLog:this.db.prepare('SELECT * FROM hr_events WHERE game_code=? ORDER BY id').all(c),history:this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? ORDER BY id').all(c),createdAt:gEnd.created_at});return true;}
  sendMessage(c,p,channel,body){const g=this.game(c),player=this.requirePlayer(c,p);this.authorizeChannel(g,player,channel,true);return this.insertMessage(c,channel,null,p,player.name,String(body||'').trim().slice(0,1000),'player');}
  insertMessage(c,ch,recipient,p,author,body,kind,meta=null){if(!body)throw new Error('Message is empty');const x=this.db.prepare('INSERT INTO hr_messages(game_code,channel,recipient_code,player_code,author,body,kind,created_at,meta) VALUES(?,?,?,?,?,?,?,?,?)').run(c,ch,recipient,p,author,body,kind,this.now(),meta?JSON.stringify(meta):null);return this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt,meta FROM hr_messages WHERE id=?').get(x.lastInsertRowid);}
  system(c,b){const m=this.insertMessage(c,'public',null,null,'The Vox',b,'system');this.emitChatMessage(c,m);return m;} privateSystem(c,p,b,meta=null){const m=this.insertMessage(c,'private',p,null,'The Vox',b,'system',meta);this.emitChatMessage(c,m);return m;} factionSystem(c,b){const m=this.insertMessage(c,'faction',null,null,'The Vox',b,'system');this.emitChatMessage(c,m);return m;}
  flavor(category,vars={}){const list=this.config?.deathFlavor?.[category];if(!list||!list.length)return '';let t=list[Math.floor(this.random()*list.length)];for(const[k,v]of Object.entries(vars))t=t.split(`{${k}}`).join(String(v));return t;}
  historyMessages(c,p,ch='public',before=Number.MAX_SAFE_INTEGER,limit=50){const g=this.game(c);const player=this.player(c,p);if(!player){if(g.phase==='lobby'||ch!=='public')throw new Error('Access denied');}else{this.authorizeChannel(g,player,ch,false);}const cap=Math.min(100,Number(limit)||50);const rows=this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? AND channel=? AND id<? ORDER BY id DESC LIMIT ?').all(c,ch,Number(before)||Number.MAX_SAFE_INTEGER,cap+1).reverse();const hasMore=rows.length>cap;return {messages:hasMore?rows.slice(0,cap):rows,hasMore};}
  authorizeChannel(g,p,ch,write){if(!['public','faction','graveyard'].includes(ch))throw new Error('Unknown channel');if(ch==='faction'&&p.faction!=='heretic')throw new Error('Faction channel denied');if(ch==='graveyard'&&p.alive)throw new Error('Graveyard denied');if(write&&ch==='public'&&(!p.alive||g.phase==='night'))throw new Error('Public chat is closed');if(write&&ch==='faction'&&g.phase!=='night')throw new Error('Faction chat is night-only');}
    // TODO(heresy-spec): Q28 — Day 1 votingEnabled = false. Remove when gate is wired.
  state(c,viewerCode){const g=this.requireGame(c),viewer=this.requirePlayer(c,viewerCode),ended=g.status==='ended',players=this.players(c).map(p=>({playerCode:p.player_code,name:p.name,alive:!!p.alive,ready:!!p.ready,connected:!!p.connected,isHost:p.player_code===g.host_code,crippleTier:p.cripple_tier,confessed:!!p.confessed,...((p.player_code===viewerCode||ended)?{role:p.role_id?this.role(p.role_id):null,faction:p.faction}:{}),...(viewer.faction==='heretic'&&p.faction==='heretic'?{faction:'heretic'}:{})}));const privateMessages=this.db.prepare("SELECT id,author,body,kind,created_at AS createdAt,meta FROM hr_messages WHERE game_code=? AND channel='private' AND recipient_code=? ORDER BY id").all(c,viewerCode).map(m=>({...m,meta:m.meta?JSON.parse(m.meta):null}));const votingEnabled=g.phase==='day'?g.round!==1:true;return {code:c,mode:g.mode,phase:g.phase,dayStage:g.day_stage,status:g.status,round:g.round,deadline:g.deadline,winner:g.winner,maxDrift:g.max_drift,dayMs:g.day_ms,nightMs:g.night_ms,isHost:g.host_code===viewerCode,players,me:players.find(x=>x.playerCode===viewerCode),votes:g.phase==='day'?this.voteState(c):[],myAction:this.db.prepare('SELECT kind,target_code AS targetCode,variant FROM hr_actions WHERE game_code=? AND round=? AND actor_code=?').get(c,g.round,viewerCode)||null,lastProtectTarget:getLastProtectTarget(this.db,g.code,viewerCode),privateMessages,pendingInterrogation:g.day_stage==='response'?{targetCode:g.last_interrogated_target,tier:g.last_interrogation_tier,canRespond:g.last_interrogated_target===viewerCode}:null,votingEnabled,...(g.phase==='lobby'?{compositionLabel:`${players.length}-operative doctrine`}:{})};}
  spectate(c){const g=this.requireGame(c);if(g.phase==='lobby')throw new Error('Game has not started yet');const ended=g.status==='ended';const players=this.players(c).map(p=>({playerCode:p.player_code,name:p.name,alive:!!p.alive,ready:!!p.ready,connected:!!p.connected,isHost:p.player_code===g.host_code,crippleTier:p.cripple_tier,confessed:!!p.confessed,...(ended?{role:p.role_id?this.role(p.role_id):null,faction:p.faction}:{})}));return {code:c,mode:g.mode,phase:g.phase,dayStage:g.day_stage,status:g.status,round:g.round,deadline:g.deadline,winner:g.winner,maxDrift:g.max_drift,dayMs:g.day_ms,nightMs:g.night_ms,isHost:false,players,me:null,votes:g.phase==='day'?this.voteState(c):[],myAction:null,lastProtectTarget:null,privateMessages:[],pendingInterrogation:null,votingEnabled:g.phase==='day'?g.round!==1:false,isSpectator:true};}
  adminRole(id){if(!id)return null;const r=this.config.roles.get(id);return r?{id:r.id,displayName:r.displayName,faction:r.faction,claim:r.claim,driftWeight:r.driftWeight,objective:r.objective,ability:r.ability}:null;}
  adminPlayer(p,g){return {playerCode:p.player_code,name:p.name,seat:p.seat,roleId:p.role_id,role:this.adminRole(p.role_id),faction:p.faction,drift:p.drift,alive:!!p.alive,ready:!!p.ready,connected:!!p.connected,isHost:p.player_code===g.host_code,isBot:!!p.is_bot,crippleTier:p.cripple_tier,tier1UntilRound:p.tier1_until_round,confessed:!!p.confessed,confessionTokenRound:p.confession_token_round,skipNextNight:!!p.skip_next_night,joinedAt:p.joined_at};}
  adminGameSummary(g){const players=this.players(g.code),messages=this.db.prepare('SELECT COUNT(*) AS count FROM hr_messages WHERE game_code=?').get(g.code).count,events=this.db.prepare('SELECT COUNT(*) AS count FROM hr_events WHERE game_code=?').get(g.code).count,actions=this.db.prepare('SELECT COUNT(*) AS count FROM hr_actions WHERE game_code=?').get(g.code).count,votes=this.db.prepare('SELECT COUNT(*) AS count FROM hr_votes WHERE game_code=?').get(g.code).count;return {code:g.code,mode:g.mode,phase:g.phase,dayStage:g.day_stage,status:g.status,round:g.round,deadline:g.deadline,winner:g.winner,maxDrift:g.max_drift,hintProfile:g.hint_profile,createdAt:g.created_at,updatedAt:g.updated_at,hostCode:g.host_code,playerCount:players.length,aliveCount:players.filter(p=>p.alive).length,connectedCount:players.filter(p=>p.connected).length,readyCount:players.filter(p=>p.ready).length,averageDrift:players.length?players.reduce((sum,p)=>sum+p.drift,0)/players.length:0,maxPlayerDrift:players.length?Math.max(...players.map(p=>p.drift)):0,hereticCount:players.filter(p=>p.faction==='heretic').length,loyalistCount:players.filter(p=>p.faction==='loyalist').length,messageCount:messages,eventCount:events,actionCount:actions,voteCount:votes};}
  adminOverview(){const games=this.db.prepare('SELECT * FROM hr_games ORDER BY updated_at DESC').all().map(g=>this.adminGameSummary(g));return {games,roles:this.roleDefinitions().map(r=>({id:r.id,displayName:r.displayName,faction:r.faction,claim:r.claim,driftWeight:r.driftWeight,objective:r.objective,ability:r.ability})),totals:{games:games.length,active:games.filter(g=>g.status==='active').length,lobby:games.filter(g=>g.status==='lobby').length,ended:games.filter(g=>g.status==='ended').length,players:games.reduce((sum,g)=>sum+g.playerCount,0),messages:games.reduce((sum,g)=>sum+g.messageCount,0)}};}
  adminGame(c){const g=this.requireGame(c),players=this.players(c).map(p=>this.adminPlayer(p,g)),actions=this.db.prepare('SELECT round,actor_code AS actorCode,kind,target_code AS targetCode,variant,data,created_at AS createdAt FROM hr_actions WHERE game_code=? ORDER BY round DESC,created_at DESC').all(c).map(a=>({...a,data:a.data?JSON.parse(a.data):null})),votes=this.db.prepare('SELECT round,stage,voter_code AS voterCode,choice,created_at AS createdAt FROM hr_votes WHERE game_code=? ORDER BY round DESC,created_at DESC').all(c),messages=this.db.prepare('SELECT id,channel,recipient_code AS recipientCode,player_code AS playerCode,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? ORDER BY id DESC LIMIT 200').all(c).reverse(),events=this.db.prepare('SELECT id,type,payload,created_at AS createdAt FROM hr_events WHERE game_code=? ORDER BY id DESC LIMIT 200').all(c).reverse().map(e=>({...e,payload:e.payload?JSON.parse(e.payload):null}));return {game:this.adminGameSummary(g),players,actions,votes,messages,events};}
  adminUpdatePlayer(c,p,updates={}){const existing=this.requirePlayer(c,p),g=this.requireGame(c),fields=[],values=[];const bools={alive:'alive',ready:'ready',connected:'connected',confessed:'confessed',skipNextNight:'skip_next_night'};for(const [input,column] of Object.entries(bools))if(updates[input]!==undefined){fields.push(`${column}=?`);values.push(updates[input]?1:0);}if(updates.drift!==undefined){fields.push('drift=?');values.push(Math.max(0,Math.min(g.max_drift,Number(updates.drift)||0)));}if(updates.crippleTier!==undefined){fields.push('cripple_tier=?');values.push(Math.max(0,Math.min(3,Number(updates.crippleTier)||0)));}if(updates.faction!==undefined&&['loyalist','heretic'].includes(updates.faction)){fields.push('faction=?');values.push(updates.faction);}if(updates.roleId!==undefined){if(updates.roleId&& !this.config.roles.has(updates.roleId))throw new Error('Unknown role');fields.push('role_id=?');values.push(updates.roleId||null);}if(!fields.length)return this.adminPlayer(existing,g);this.db.prepare(`UPDATE hr_players SET ${fields.join(', ')} WHERE game_code=? AND player_code=?`).run(...values,c,p);return this.adminPlayer(this.player(c,p),g);}
  adminEndGame(c,winner='admin'){const g=this.requireGame(c);this.db.prepare("UPDATE hr_games SET phase='ended',status='ended',winner=?,deadline=NULL,updated_at=? WHERE code=?").run(String(winner||'admin').slice(0,30),this.now(),c);this.system(c,`Game ended by admin: ${winner}.`);const gEnd=this.game(c);saveGameLogSnapshot({gameLogId:c,code:c,phase:gEnd.phase,winner:gEnd.winner,round:gEnd.round,maxDrift:gEnd.max_drift,mode:gEnd.mode,status:gEnd.status,players:this.players(c).map(p=>({id:p.player_code,name:p.name,hero:p.role_id||null,playerCode:p.player_code,seat:p.seat,roleId:p.role_id||null,faction:p.faction,drift:p.drift,alive:!!p.alive,crippleTier:p.cripple_tier,isBot:!!p.is_bot})),debugLog:this.db.prepare('SELECT * FROM hr_events WHERE game_code=? ORDER BY id').all(c),history:this.db.prepare('SELECT id,channel,author,body,kind,created_at AS createdAt FROM hr_messages WHERE game_code=? ORDER BY id').all(c),createdAt:gEnd.created_at});return this.adminGame(c);}
  adminDeleteGame(c){this.requireGame(c);this.db.transaction(()=>{for(const table of ['hr_actions','hr_votes','hr_messages','hr_usage','hr_events','hr_players'])this.db.prepare(`DELETE FROM ${table} WHERE game_code=?`).run(c);this.db.prepare('DELETE FROM hr_games WHERE code=?').run(c);})();return {deleted:true};}
  due(){return this.db.prepare("SELECT code FROM hr_games WHERE status='active' AND deadline IS NOT NULL AND deadline<=?").all(this.now()).map(x=>x.code);}
  // ── Bots ───────────────────────────────────────────────────────────────────
  // Spawn authorisation: only callers holding the bot-manager's BOT_API_KEY reach
  // adminSpawnBot/adminDespawnBot (the engine treats those as privileged internal
  // calls; /api/bots/* validates the bearer token before reaching these).
  // Lobby-only gate per locked Q-BOT spawn rule.
  generateBotPlayerCode(){const existing=new Set(this.db.prepare('SELECT player_code FROM hr_players').all().map(x=>x.player_code));let code;do{code='HR-BOT-'+crypto.randomBytes(8).toString('hex');}while(existing.has(code));return code;}
  adminSpawnBot(code,{name='Heretic Bot',seatHint=null}={}){
    const g=this.requireGame(code);
    if(g.phase!=='lobby')throw new Error('Bots can only be added while the Conclave is in the lobby');
    const players=this.players(code);
    const botCount=players.filter(p=>p.is_bot).length;
    const MAX_BOTS_PER_GAME=Number(process.env.MAX_BOTS_PER_GAME)||4;
    if(botCount>=MAX_BOTS_PER_GAME)throw new Error(`Bot limit (${MAX_BOTS_PER_GAME} per Conclave) reached`);
    if(players.length>=12)throw new Error('Conclave is full');
    let seat;
    if(seatHint!=null&&seatHint!==''){const s=Math.max(0,Number(seatHint)|0);if(s>=12||players.some(p=>p.seat===s))throw new Error('Requested seat is taken or out of range');seat=s;}
    else{const taken=new Set(players.map(p=>p.seat));seat=0;while(taken.has(seat))seat++;}
    const playerCode=this.generateBotPlayerCode();
    this.db.prepare('INSERT INTO hr_players(game_code,player_code,name,seat,joined_at,is_bot,ready) VALUES(?,?,?,?,?,1,1)').run(code,playerCode,sanitizePlayerName(name)||'Heretic Bot',seat,this.now());
    return {playerCode,seat,isBot:true,name:sanitizePlayerName(name)||'Heretic Bot',conclaveCode:code};
  }
  adminDespawnBot(code,playerCode){
    const p=this.requirePlayer(code,playerCode);
    if(!p.is_bot)throw new Error('Not a bot');
    const g=this.requireGame(code);
    if(g.phase!=='lobby')throw new Error('Bots can only be removed while the Conclave is in the lobby');
    this.db.prepare('DELETE FROM hr_players WHERE game_code=? AND player_code=?').run(code,playerCode);
    return {despawned:true,playerCode,conclaveCode:code};
  }
  botIds(c){return this.players(c).filter(p=>p.is_bot).map(p=>p.player_code);}
  botSessionInit(c,playerCode){
    const g=this.requireGame(c),p=this.requirePlayer(c,playerCode);
    if(!p.is_bot)return null;
    if(g.phase==='lobby')return {kind:'session_init',botId:playerCode,playerCode,role:null,faction:null,claim:null,round:0,phase:'lobby',votingEnabled:false,alivePlayers:this.players(c).map(x=>x.player_code),deadPlayers:[],publicAnnouncements:[],botIds:this.botIds(c)};
    const role=p.role_id?this.role(p.role_id):null;
    return {kind:'session_init',botId:playerCode,playerCode,role:role?.id||null,faction:p.faction,claim:role?.claim||null,round:g.round,phase:g.phase,votingEnabled:g.phase==='day'?g.round!==1:false,alivePlayers:this.players(c).filter(x=>x.alive).map(x=>x.player_code),deadPlayers:this.players(c).filter(x=>!x.alive).map(x=>x.player_code),publicAnnouncements:[],botIds:this.botIds(c)};
  }
  event(c,t,p){this.db.prepare('INSERT INTO hr_events(game_code,type,payload,created_at) VALUES(?,?,?,?)').run(c,t,JSON.stringify(p),this.now());}
  requireGame(c){const g=this.game(c);if(!g)throw new Error('Game not found');return g;}requirePlayer(c,p){const x=this.player(c,p);if(!x)throw new Error('Not a member');return x;}requireAlive(c,p){const x=this.requirePlayer(c,p);if(!x.alive)throw new Error('Dead players cannot do that');return x;}requireHost(c,p){const g=this.requireGame(c);if(g.host_code!==p)throw new Error('Host permission required');return g;}
}
