<template>
  <section class="game-page">
    <div class="phase-strip" :class="game.phase"><div><span class="phase-icon">{{ game.phase==='night'?'☾':game.phase==='ended'?'†':'☼' }}</span><div><span class="eyebrow">{{ stageKicker }}</span><strong>{{ stageTitle }}</strong></div></div><div class="phase-time"><small>PHASE ENDS IN</small><strong>{{ timeLeft }}</strong></div></div>
    <nav class="mobile-tabs"><button v-for="tab in ['roster','chat','orders']" :key="tab" :class="{active:mobileTab===tab}" @click="mobileTab=tab">{{ tab }}</button></nav>
    <div class="game-grid">
      <aside class="panel roster-panel" :class="{'mobile-hidden':mobileTab!=='roster'}"><header><h2>Conclave</h2><span>{{ alive.length }} alive</span></header><ul class="player-list"><li v-for="p in players" :key="p.playerCode" :class="{dead:!p.alive,me:p.playerCode===me?.playerCode,selected:myVote?.choice===p.playerCode,selectable:votingOpen&&p.alive&&p.playerCode!==me?.playerCode,unavailable:!p.alive||p.playerCode===me?.playerCode}" @click="voteFor(p)"><span class="avatar">{{ initial(p.name) }}</span><div><strong>{{ p.name }}</strong><span>{{ status(p) }}</span></div><small v-if="votingOpen&&p.alive" class="vote-count">{{ targetVoteCount(p.playerCode) }}/{{ voteThreshold }}</small><i :class="{online:p.connected}"></i></li></ul><template v-if="votingOpen"><button class="ghost wide" :class="{selected:myVote?.choice==='skip'}" @click="castVote('skip')">Stand down <small>{{ targetVoteCount('skip') }}/{{ voteThreshold }}</small></button><button v-if="myVote" class="ghost wide" @click="$emit('retract-vote')">Retract vote</button></template><button class="ghost wide leave" @click="$emit('leave')">Leave session</button></aside>
      <section class="panel chat-panel" :class="{'mobile-hidden':mobileTab!=='chat'}"><div class="channel-tabs"><button v-for="c in channels" :key="c.id" :class="{active:channel===c.id}" @click="$emit('channel',c.id)">{{ c.label }}<small>{{ c.note }}</small></button></div><button v-if="messages.length && hasMore" class="load-history" @click="$emit('history',messages[0]?.id)">Load earlier transmissions</button><div ref="feed" class="message-feed"><div v-if="!messages.length" class="empty-chat"><strong>No transmissions recorded</strong></div><article v-for="m in messages" :key="m.id" :class="['message',{system:m.kind==='system',vote:m.kind==='vote'}]"><span v-if="m.kind==='system'" class="system-line">{{ m.body }}</span><template v-else><span class="avatar mini">{{ initial(m.author) }}</span><div><header><strong>{{ m.author }}</strong><time>{{ formatTime(m.createdAt) }}</time></header><p>{{ m.body }}</p></div></template></article></div><form class="composer" @submit.prevent="post"><textarea v-model.trim="draft" maxlength="1000" rows="2" :disabled="!canChat" :placeholder="canChat?'Transmit… (Enter to send, Shift+Enter for newline)':'Channel sealed'" @keydown.enter.exact.prevent="post"></textarea><button class="primary" :disabled="!draft||!canChat">Transmit</button></form></section>
      <aside class="panel orders-panel" :class="{'mobile-hidden':mobileTab!=='orders'}">
        <template v-if="game.phase==='ended'"><span class="eyebrow">FINAL JUDGEMENT</span><h2>{{ game.winner }} victory</h2><div class="reveal-list"><div v-for="p in players" :key="p.playerCode"><strong>{{ p.name }}</strong><span>{{ p.role?.displayName }}</span></div></div></template>
        <template v-else><span class="eyebrow">CLASSIFIED DOSSIER</span><div class="role-card"><h2>{{ role.displayName }}</h2><strong>{{ me.faction }}</strong><p>{{ role.ability }}</p><p>{{ role.objective }}</p></div>
          <div v-if="game.phase==='day'" class="order-block">
            <div v-if="role.actions?.day?.kind==='forgery'" class="preset"><span class="eyebrow">FORGERY · ONCE TODAY</span><label>Attributed speaker<select v-model="forgeAs"><option v-for="p in validTargets" :key="p.playerCode" :value="p.playerCode">{{ p.name }}</option></select></label><label>Forged transmission<textarea v-model="forgeBody" maxlength="500"></textarea></label><button class="ghost wide" :disabled="!forgeAs||!forgeBody" @click="forge">Plant transmission</button></div>
            <label v-if="me.crippleTier>=2">Required vote justification<textarea v-model="voteJustification" maxlength="300"></textarea></label>
            <template v-if="pending?.canRespond&&pending.tier<3"><span class="eyebrow">INTERROGATION RESPONSE</span><h2>Choose your answer</h2><button class="secondary wide" @click="$emit('respond','confess')">Confess</button><button class="ghost wide" @click="$emit('respond','resist')">Resist</button><button class="primary wide" @click="$emit('respond','refuse-break')">Refuse + Break</button></template>
            <template v-else-if="pending?.tier===3"><span class="eyebrow">FORCED CONFESSION</span><h2>Ask the crippled suspect</h2><button class="primary wide" @click="$emit('ask-confession',pending.targetCode)">Demand confession</button></template>
            <p v-else-if="pending" class="notice">Waiting for the accused to answer.</p>
          </div>
           <div v-else class="order-block"><span class="eyebrow">NIGHT DIRECTIVE</span><h2>{{ actionLabel }}</h2><template v-if="hasNightAction"><label v-if="variants.length">Intensity<select v-model="variant"><option v-for="v in variants" :key="v" :value="v">{{ intensityLabel(v) }}</option></select></label><div class="targets"><button v-for="p in actionTargets" :key="p.playerCode" :class="{selected:game.myAction?.targetCode===p.playerCode}" @click="act(p.playerCode)"><span>{{ initial(p.name) }}</span>{{ p.name }}</button></div><button v-if="game.myAction" class="ghost wide" @click="$emit('retract-action')">Retract directive</button></template><p v-else class="notice">No directive. Skipping the night counts as sleep.</p></div>
        </template>
      </aside>
    </div>
  </section>
</template>
<script setup>
import { computed,nextTick,ref,watch } from 'vue';
const props=defineProps({game:{type:Object,required:true},me:Object,messages:{type:Array,default:()=>[]},channel:String,busy:Boolean,now:Number,hasMore:{type:Boolean,default:true}});const emit=defineEmits(['channel','send','history','vote','retract-vote','action','retract-action','respond','ask-confession','leave']);
const draft=ref(''),mobileTab=ref('chat'),feed=ref(null),variant=ref(''),forgeAs=ref(''),forgeBody=ref(''),voteJustification=ref('');
const players=computed(()=>props.game.players||[]),alive=computed(()=>players.value.filter(p=>p.alive)),role=computed(()=>props.me?.role||{}),nightAction=computed(()=>role.value.actions?.night),hasNightAction=computed(()=>nightAction.value&&nightAction.value.kind!=='sleep'),variants=computed(()=>nightAction.value?.variants||[]),pending=computed(()=>props.game.pendingInterrogation),validTargets=computed(()=>alive.value.filter(p=>p.playerCode!==props.me?.playerCode)),myVote=computed(()=>props.game.votes?.find(v=>v.voterCode===props.me?.playerCode)),voteThreshold=computed(()=>props.game.votes?.[0]?.threshold||Math.floor(alive.value.length/2)+1),voteCounts=computed(()=>{const counts={};for(const v of props.game.votes||[])counts[v.choice]=(counts[v.choice]||0)+1;return counts;}),votingOpen=computed(()=>props.game.phase==='day'&&!pending.value);
watch(variants,v=>variant.value=v[0]||'',{immediate:true});
let preChangeHeight=0,preChangeScrollTop=0;
watch(()=>props.messages.length,()=>{
  const el=feed.value;
  if(el){preChangeHeight=el.scrollHeight;preChangeScrollTop=el.scrollTop;}
});
watch(()=>props.messages,()=>nextTick(()=>{
  const el=feed.value;
  if(!el)return;
  const heightDelta=el.scrollHeight-preChangeHeight;
  const wasNearBottom=preChangeHeight-preChangeScrollTop-el.clientHeight<80;
  if(wasNearBottom)el.scrollTop=el.scrollHeight;
  else if(heightDelta>0)el.scrollTop=preChangeScrollTop+heightDelta;
}),{deep:false});
const actionTargets=computed(()=>alive.value.filter(p=>{if(nightAction.value?.target==='any')return true;if(p.playerCode===props.me?.playerCode){return nightAction.value?.kind==='protect';}if(nightAction.value?.target==='hostile')return p.faction!=='heretic';return true}));
const channels=computed(()=>[{id:'public',label:'Conclave',note:'public'},...(props.me?.faction==='heretic'?[{id:'faction',label:'Cabal',note:'heretics'}]:[]),...(!props.me?.alive?[{id:'graveyard',label:'Graveyard',note:'dead'}]:[])]),canChat=computed(()=>props.game.phase!=='ended'&&(props.channel!=='public'||props.game.phase!=='night')&&(props.me?.alive||props.channel==='graveyard'));
const deadline=computed(()=>props.game.deadline),timeLeft=computed(()=>{if(!deadline.value)return'—';const s=Math.max(0,Math.floor((deadline.value-props.now)/1000));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}),stageTitle=computed(()=>props.game.phase==='day'?`Day ${props.game.round} · ${props.game.dayStage}`:props.game.phase==='night'?`Night ${props.game.round}`:props.game.phase),stageKicker=computed(()=>props.game.phase==='night'?'THE LIGHT WITHDRAWS':'THE CONCLAVE SITS'),actionLabel=computed(()=>hasNightAction.value?pretty(nightAction.value.kind):'Keep the vigil');
function castVote(choice){emit('vote',{choice,justification:voteJustification.value})}
function voteFor(p){if(!votingOpen.value||!p.alive||p.playerCode===props.me?.playerCode)return;castVote(p.playerCode)}function act(targetCode){emit('action',{targetCode,variant:variant.value||undefined})}function forge(){emit('action',{asPlayerCode:forgeAs.value,body:forgeBody.value});forgeBody.value=''}function post(){if(draft.value&&canChat.value){emit('send',draft.value);draft.value=''}}function initial(n){return(n||'?')[0].toUpperCase()}function pretty(s){return String(s||'').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}function intensityLabel(v){return v==='T1'?'T1 — Soft':v==='T2'?'T2 — Standard':v==='T3'?'T3 — Brutal':pretty(v)}function status(p){if(!p.alive)return'Deceased';if(p.crippleTier)return`Interrogation Tier ${p.crippleTier}`;return p.connected?'Observing':'Vox lost'}function formatTime(t){return t?new Date(t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}function targetVoteCount(choice){return voteCounts.value[choice]||0}
</script>
